LICENSE
Note, we think the bazel-lib is so useful and reduces our toil in maintaining rules like rules_nodejs, and want other rules authors to feel comfortable contributing here, so we are choosing the same license as that repository rather than a commercial license here.
=> license under apache 2

.github/workflows/workspace_snippet.sh
Adds the missing `.bzl` extension. Copying these verbatim results in the following error:
```
bazel build //...
ERROR: /Users/matt/workspace/multi_python_workspace_example/WORKSPACE:19:6: in load statement: The label must reference a file with extension '.bzl'
ERROR: error loading package '': malformed load statements
INFO: Elapsed time: 0.120s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
=> fix: add missing .bzl suffix in release template loads

.prettierignore, docs/BUILD.bazel, docs/write_source_files.md, lib/BUILD.bazel, lib/private/BUILD.bazel, lib/private/fail_with_message_test.bzl, lib/private/write_source_files.bzl, lib/tests/write_source_files/BUILD.bazel, lib/tests/write_source_files/a.js, lib/tests/write_source_files/a2.js, lib/tests/write_source_files/b.js, lib/tests/write_source_files/b2.js, lib/tests/write_source_files/write_source_files_test.bzl, lib/write_source_files.bzl
Rule to update a file in the source tree.
This is a copy of @gregmagolan's implementation with some changes to use more rules rather than macros. I want to have a look over Chuck's updatesrc implementation to see what's different and how we can combine them before we go ahead with this.
=> feat: write_source_files

.github/workflows/workspace_snippet.sh, internal_deps.bzl
Required per https://github.com/bazel-contrib/SIG-rules-authors/issues/11
=> chore: Update github archive URLs to have stable SHAs

docs/write_source_files.md, lib/private/write_source_files.bzl, lib/tests/write_source_files/BUILD.bazel, lib/tests/write_source_files/subdir/BUILD.bazel, lib/tests/write_source_files/subdir/c.js, lib/tests/write_source_files/subdir/subsubdir/BUILD.bazel, lib/tests/write_source_files/subdir/subsubdir/d.js, lib/write_source_files.bzl
@gregmagolan @alexeagle 
`write_source_files` now accepts `deps` on other write_source_files targets so it can be used recursively to create hierarchies of update groups, or just a bunch of targets for individual files and one master update at the root.
=> feat: bulk updates for write_source_files

lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl, lib/private/write_source_file.bzl
Same fix as https://github.com/bazelbuild/rules_nodejs/pull/3383 but we have more instances of it in bazel-lib.
For reference, the cp -r option is historic and discouraged on macos. It differs from cp -r on linux.
https://man7.org/linux/man-pages/man1/cp.1.html
https://ss64.com/osx/cp.html
=> fix: use -R instead of -r in cp calls so macos & linux behavior is the same

docs/BUILD.bazel, docs/copy_directory.md, lib/BUILD.bazel, lib/copy_directory.bzl, lib/private/BUILD.bazel, lib/private/copy_directory.bzl, lib/tests/copy_directory/BUILD.bazel
@gregmagolan @alexeagle 
https://github.com/aspect-build/bazel-lib/issues/62
https://buildkite.com/bazel/bazel-lib/builds?branch=kormide%3Acopy_directory
Should I remove directory support from `copy_file` if we want to upstream this to skylib?
=> feat: add copy_directory

docs/BUILD.bazel, docs/repo_utils.md, lib/BUILD.bazel, lib/private/BUILD.bazel, lib/private/patch copy.bzl, lib/private/patch.bzl, lib/private/repo_utils.bzl, lib/repo_utils.bzl
This is going to be needed for `npm_import` in rules_js as we want to patch in a sub-directory and not at the external repository root
=> feat: add repo_utils with fork of @bazel_tools patch function that takes a working_directory argument

docs/copy_directory.md, lib/copy_directory.bzl, lib/private/copy_directory.bzl
Needed for the implementation of the new nodejs_package rule in rules_js to copy an npm package to a TreeArtifact in the virtual store:
```
if ctx.file.src:
virtual_store_out = ctx.actions.declare_directory(
"node_modules/{virtual_store_root}/{virtual_store_name}/node_modules/{package_name}".format(
package_name = ctx.attr.package_name,
virtual_store_name = virtual_store_name,
virtual_store_root = VIRTUAL_STORE_ROOT,
)
)
copy_directory_action(ctx, ctx.file.src, virtual_store_out, ctx.attr.is_windows)
```
=> feat: add copy_directory_action help to the public API

docs/copy_to_bin.md, lib/copy_to_bin.bzl
=> fix: add copy_file_to_bin_action and copy_files_to_bin_actions to //lib:copy_to_bin.bzl

lib/private/expand_make_vars.bzl, lib/tests/expand_make_vars_test.bzl
=> feat: add some additional make variable substitutions for common useful values in the context

lib/windows_utils.bzl
=> feat: add create_windows_native_launcher_script to lib/windows_utils.bzl

lib/private/BUILD.bazel, lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl
Inspired by https://github.com/bazelbuild/rules_nodejs/pull/3410
Copying file & directories is entirely IO-bound and there is no point doing this work
remotely.
Also, remote-execution does not allow source directory inputs, see
https://github.com/bazelbuild/bazel/commit/c64421bc35214f0414e4f4226cc953e8c55fa0d2 So we must
not attempt to execute remotely in that case.
There is also no point pulling the output file or directory from the remote cache since the
bytes to copy are already available locally. Conversely, no point in writing to the cache if
no one has any reason to check it for this action.
Read and writing to disk cache is disabled as well primarily to reduce disk usage on the local
machine. A disk cache hit of a directory copy could be slghtly faster than a copy since the
disk …
=> fix: improve execution requirements of all copy files/directory rules for better perf

.github/workflows/create-bcr-entry.mjs
I think I can re-run the last BCR action after this merges since it checks out the current version of the script, so hopefully we don't need to publish more releases.
=> debug: add some logging to debug bcr action

.github/workflows/bcr/source.template.json, .github/workflows/create-bcr-entry.mjs
My downloader didn't follow http `302`, which for some reason I wasn't running into locally.
=> fix: fix a bug where bcr action wouldn't follow redirects to artifact

README.md
It's not really clear what rules we provide to someone visiting our github landing page.
=> docs: link to docsite in README

.github/workflows/bcr.yml
I read the docs wrong on this field. It doesn't take a username but a `Name <email>` format. Since I don't have access to the actor's name/email in the action, I'm just going to let it default for now to the github actions bot.
This was causing the bcr workflow to fail.
=> ci: remove committer for auto-bcr

docs/docs.md, lib/private/docs.bzl, lib/write_source_files.bzl
Also simplify `//docs:update` target to use a single `write_source_files`.
Previously the failure would have shown,
```
$ cat /private/var/tmp/_bazel_greg/d429ac343bccdd9460beaa3e7ac46428/execroot/aspect_bazel_lib/bazel-out/darwin-fastbuild/testlogs/docs/update_10_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //docs:update_10_test
-----------------------------------------------------------------------------
7c7
< ## write_source_files
---
> ## write_source_files!
FAIL: files "docs/write_source_files-docgen.md" and "docs/write_source_files.md" differ. 
//docs:write_source_files.md is out of date. To update this and other generated files, run:
bazel run //docs:update_10
```
with this fix the error is now
```
$ cat …
```
=> fix: set correct suggested_update_target for write_source_files macros with multiple files

MODULE.bazel, e2e/bzlmod/MODULE.bazel, lib/private/jq.bzl
After this we should be green and ready for a 1.0 release if we want to do that.
https://buildkite.com/bazel/bazel-lib
=> fix: buildifier lint errors

lib/private/copy_to_directory.bzl, lib/tests/copy_to_directory/BUILD.bazel
When two srcs have the same nested folder, we need to correct the permissions like bazel's sandbox would.
Also remove the -f on the copy operations, as those would hide mistakes where one input (source or generated) is overwritten by another
=> fix: copy_to_directory repairs read-only file permissions

lib/private/directory_path.bzl, lib/private/patch.bzl, lib/private/paths.bzl, lib/private/utils.bzl, lib/private/write_source_file.bzl
I always end up first reading the string with the %s or {} tokens instead of the actual error on these
=> chore: cleanup fail msgs with substitutions for cleaner error logs

.bazelrc, lib/tests/write_source_files/BUILD.bazel, lib/tests/write_source_files/skylib_LICENSE
Turns out `diff_test` (skylib's and our fork's) relies on legacy external runfiles on Windows. We can either remove this flag, or we can try to fix the batch script to support regular runfiles trees.
=> fix: fix a bug where write_source_files diff_test fails on windows when a source is from an external repository

.github/workflows/bcr.yml
The PRs to bcr work (https://github.com/bazelbuild/bazel-central-registry/pull/108) but this part of the action fails, making it red in our actions logs. We don't have the admin rights to assign the PR to anyone.
=> fix: don't set assignees for bcr pr

lib/jq.bzl, lib/private/jq.bzl, lib/private/jq_toolchain.bzl, lib/tests/jq/BUILD.bazel
This lets you have a file in the output tree with the same path as a source file, but modified.
Came up while translating an angular `ng-package.json` file to fix up the `dest` path. We don't want to change the source file name, as Angular CLI generates it, and we can't change the output file name.
=> feat: let jq act like copy_to_bin

docs/write_source_files.md, lib/write_source_files.bzl
As discussed online, adding a note to the docgen about linting/formatting
=> docs: add a note about excluding from linters/formatters

lib/private/jq_toolchain.bzl, lib/private/yq_toolchain.bzl
Is this right? I haven't done much with platforms before.
=> fix: remote target_compatible_with from jq and yq toolchains

lib/private/diff_test.bzl
Skylib fixed this [issue](https://github.com/bazelbuild/bazel-skylib/issues/376) I raised, so adding their patch here. This will allow us remove this [this flag](https://github.com/aspect-build/rules_js/blob/main/.bazelrc.common#L24) for rules_js and disable legacy external runfiles for Windows as well.
=> fix: patch diff_test with runfiles fix

lib/private/directory_path.bzl
Fixes https://github.com/aspect-build/bazel-lib/issues/122.
The error message was already improved in https://github.com/aspect-build/bazel-lib/commit/128f7c63fbe3e2d3ead83ff7d6bb09728666acf2.
=> fix: improve error message in directory_path when directory does not exist

lib/tests/copy_to_directory/BUILD.bazel
There is coverage in glob_match for this but might as well be robust and cover in copy_to_directory as well
=> chore: add '?' pattern to test cases of copy_to_directory

lib/private/copy_to_directory.bzl
Since we're comparing these paths this will prevent an accidental `/./` segment from sneaking in a breaking our comparison
=> chore: normalize src and outputs paths in copy_to_directory

.aspectci/config.yaml
The `/dev/null` is a pseudo-device file that's not executable. If we expect a call to `CC` to actually fail, then `/bin/false` is the right file.
=> fix: /bin/false instead of /dev/null

docs/expand_make_vars.md, lib/BUILD.bazel, lib/expand_make_vars.bzl, lib/private/BUILD.bazel, lib/private/expand_locations.bzl, lib/private/expand_template.bzl, lib/private/expand_variables.bzl, lib/private/params_file.bzl, lib/private/run_binary.bzl, lib/tests/BUILD.bazel, lib/tests/expand_make_vars_test.bzl
The test for this was accidentally working since `BINDIR` was added to substitutions via `**ctx.var`. With the substitution updated to `"{BINDIR}": "$(BINDIR)"` it fails. This fixes the expand_template rule to use the `expand_variables` helper.
A follow-up update to this rule would add suport for substitution of stamp vars if a `stamp` attribute is set to `True`. This, however, would require an action so will leave it for a follow-up.
=> fix: fix make var expansion in expand_template

docs/testing.md, docs/utils.md, lib/BUILD.bazel, lib/private/BUILD.bazel, lib/private/diff_test.bzl, lib/private/utils.bzl, lib/testing.bzl, lib/tests/BUILD.bazel, lib/tests/copy_to_bin/BUILD.bazel, lib/tests/copy_to_directory/BUILD.bazel, lib/tests/copy_to_directory_action/BUILD.bazel, lib/tests/expand_make_vars_test.bzl, lib/tests/glob_match_test.bzl, lib/tests/paths_test.bzl, lib/tests/stamping/BUILD.bazel, lib/tests/utils_test.bzl, lib/tests/write_source_files/write_source_file_test.bzl, lib/utils.bzl
I recently enabled --test_verbose_timeout_warnings and that caused a bunch of warnings in our build.
This fixes it, and adds a utility for us or others to make test-wrapping macros that set to short by default.
Also happens to add more bzl_library targets since I ran gazelle. Will add gazelle freshness check to Aspect CI so it's solved globally.
=> chore: set test timeouts to short

docs/copy_to_directory.md, lib/private/copy_to_directory.bzl, lib/private/glob_match.bzl, lib/private/output_files.bzl, lib/tests/copy_to_directory_action/pkg.bzl
I noticed `copy_to_directory_action` consuming 3-5s in the angular-cli analysis phase, making the analysis phase itself often 30s.
First commit: mainly reducing the number of `depset.to_list()` calls. Seemed to improve performance by at most 5% so maybe this case of `to_list()` isn't done on large enough `depset`s to make a big difference?
Second commit: in ~~go~~ python (and go) passing arrays as params clones them, where a slice is a reference to the array. So switching from arrays to slices avoid cloning the arrays within the file loop. This made the analysis phase in my test go from 30s to 10s...
=> copy_to_directory performance improvements

WORKSPACE, docs/copy_directory.md, docs/copy_file.md, docs/copy_to_bin.md, docs/copy_to_directory.md, lib/private/BUILD.bazel, lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_bin.bzl, lib/private/copy_to_directory.bzl, lib/private/local_config_platform.bzl, lib/tests/copy_to_directory_action/pkg.bzl
Relies on checking `HOST_CONTRAINTS` from
```
load("@local_config_platform//:constraints.bzl", "HOST_CONSTRAINTS")
```
to figure out the host platform.
Since these actions all have "local" execution requirements then we can assume the host platform is the execution platform
=> fix: fix host platform detection on all copy actions which always run locally

WORKSPACE, lib/BUILD.bazel, lib/private/BUILD.bazel, lib/private/copy_common.bzl, lib/private/local_config_platform.bzl, lib/repositories.bzl
Downstream rules will need to add this to their WORKSPACE if they are loading from @aspect_bazel_lib copy rules and 
generating stardoc:
```
load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")
aspect_bazel_lib_dependencies()
```
=> fix: fix bzl_library breakage created with load from @local_config_platform in copy rules

.github/workflows/release.yml
Recall that for the Publish to BCR app to pick up a release author (to use them as the commit author), the release needs to be done by a human rather than a bot.
Doing this temporarily until we change how our release automation works.
=> fix: use person as release author

internal_deps.bzl
This is from the https://github.com/bazel-contrib/rules-template template but we don't seem to use it.
=> chore(deps): remove build_bazel_integration_testing

lib/private/local_config_platform.bzl
The current reimplementation assumed everyone one was on `x86_64`, which, well, isn't the case and led to errors such as:
```
ERROR: /private/var/tmp/_bazel_matt/6659d1da76c274502913a8a29ab51672/external/bazel_tools/src/tools/launcher/BUILD:9:14: Target '@bazel_tools//src/tools/launcher:launcher' depends on toolchain '@llvm_toolchain//:cc-clang-x86_64-darwin', which cannot be found: no such target '@llvm_toolchain//:cc-clang-x86_64-darwin': target 'cc-clang-x86_64-darwin' not declared in package '' (did you mean 'cc-clang-arm64-darwin'?) defined by /private/var/tmp/_bazel_matt/6659d1da76c274502913a8a29ab51672/external/llvm_toolchain/BUILD.bazel'
```
Make the impl generic and pass though the arch and os.
Unblocks https://github.com/aspect-build/silo/pull/374
=> fix: handle other CPU architectures in local_config_platform

.bcr/metadata.template.json
This is needed to match what's in the upstream BCR now
=> chore: declare bzlmod repository

lib/private/utils.bzl, lib/tests/utils_test.bzl
This is needed for rules_js e2e/bzlmod to go green with Bazel 6.0.0rc1
=> fix: use bzlmod @@ in to_label if Bazel version is 6 or greater

docs/testing.md, lib/BUILD.bazel, lib/testing.bzl, lib/tests/write_source_files/BUILD.bazel
It's a simple way to make an executable example demonstrate what outputs a rule produces. See https://github.com/aspect-build/rules_ts/pull/214 for an example usage in the real world.
=> feat: add assert_outputs

docs/glob_match.md, lib/glob_match.bzl, lib/private/copy_to_directory.bzl, lib/private/glob_match.bzl, lib/tests/glob_match_test.bzl
df09e9c720e49c54c10478636cbaf428e8cadb7a gets my basic copy test (no globs) from 60s to ~11s. The rest is some basic tests and cleanup that should make it easier to avoid more perf issues in the future (just putting the quick-returns in a common location etc).
The last commit might be a breaking change and we shouldn't do it? But an empty glob really is invalid...
=> perf: do not execute glob for non-glob copy_to_directory root_paths/replace_prefix params

lib/private/docs/BUILD.bazel, lib/private/local_config_platform.bzl
Emulates what the `@local_config_platform` repo will look like after https://github.com/bazelbuild/bazel/pull/16665 lands
=> refactor: move bzl_library target out of @local_config_platform and just use exports_files in there instead

.aspect/cli/plugins.yaml, .bazeliskrc, .github/workflows/ci.yaml
Assuming you are using Bazelisk, this causes it to fetch Aspect's CLI and use that to wrap Bazel
Note, we might want to update Renovate someday to understand this file so users are more likely to stay on current versions.
=> feat: install Aspect CLI for all users

lib/private/glob_match.bzl
Turns out the `_split_on(GLOB_CHARS)` function is expensive so it is better to short-circuit before calling that
=> perf: optimize glob_match if the expression does not have any glob symbols

MODULE.bazel
Version no longer needed in the MODULE.bazel file thanks to @kormide's wizardry in the bzlmod bot
=> chore: unrelease

e2e/write_source_files.sh, e2e/write_source_files_root.sh, e2e/write_source_files_subdir.sh, e2e/write_source_files_symlinks.sh, lib/private/copy_directory.bzl
```
-R      Attempt to remove the file hierarchy rooted in each file argument.  The -R option implies the -d option.  If the -i option is specified, the user is prompted
for confirmation before each directory's contents are processed (as well as before the attempt is made to remove the directory).  If the user does not
respond affirmatively, the file hierarchy rooted in that directory is skipped.
-r      Equivalent to -R.
```
=> refactor: use rm -R instead -r as it is the primary option and lowercase -r is the alias

lib/tests/transitions/BUILD.bazel
Same bug fix as on the platform below this, but this surfaces on OSX and causes the build to fail. Last PR was only tested on Linux.
=> fix: fix a bug where transition tests required cpp toolchain on osx

tools/BUILD.bazel, tools/copy_to_directory/BUILD.bazel, tools/copy_to_directory/main.go, tools/create_release.sh, tools/hashes.bzl, tools/release.bzl, tools/sha256sum/BUILD.bazel, tools/sha256sum/main.go
We've done this in silo & in the OSS aspect-cli repo. In theory we could replace the duplication in those repositories using `release.bzl` from here but I'm not making release.bzl or hashes.bzl part of the public API yet here. Could be done in the future.
=> chore: bring in multi-platform releases rules for copy_to_directory golang binary

deps.bzl, go.mod, go.sum, tools/copy_to_directory/BUILD.bazel, tools/copy_to_directory/main.go
The former is better maintained and handles the `a` matching `a/**` case properly
=> chore: switch copy_to_directory binary tool to use com_github_bmatcuk_doublestar_v4 instead of com_github_gobwas_glob

lib/tests/transitions/test_file_type_contains.sh
The `//lib/tests/transitions` tests fail on macOS unless `coreutils` package is installed. Even if the `realpath` is not necessary in this particular case, we should avoid relying on optional packages in tests.
=> Remove the use of realpath in tests

docs/jq.md, lib/BUILD.bazel, lib/jq.bzl
This is useful in rules_swc where we want to check that tsconfig.json and .swcrc have matching paths, and most users will want that too
=> feat(jq): add a diff_test helper

lib/private/utils.bzl, lib/tests/utils_test.bzl
Fix in Bazel here https://github.com/bazelbuild/bazel/commit/3f92232c17bf4aad51880c811c291ba4b5b42721 made it into Bazel 6.0.0 release
=> chore: update pre-bazel 6 work-around in utils to only apply for bazel versions < 6

tools/common/copy.go, tools/copy_directory/main.go, tools/copy_to_directory/main.go
On very large directories, the copy functions were creating unbound concurrent copies, which could reach OS limits quickly or even exhaust hardware resources. This patch solves this issue by implementing a queue and a worker pattern.
=> fix: limit copy concurrency

lib/private/copy_directory_toolchain.bzl, lib/private/copy_to_directory_toolchain.bzl
Update the toolchains to make the fix in #351 load bearing for the copy_directory & copy_to_directory rules
=> fix: update copy_directory and copy_to_directory to use binaries with copy concurrency limited

lib/private/jq_toolchain.bzl
On M1 jq will download to a `jq_darwin_amd64` toolchain repo, but the host repo tries to reference `jq_darwin_arm64`, which doesn't exist.
=> fix: fix a bug where `bazel run @jq//:jq` cannot be run on M1

lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl
I found this useful when I saw a lot of the messages and they were all the exact same. Now it shows things such as:
```
Copying files to directory client/shared/shared
```
(the BUILD is in 'client/shared', with an `npm_package` named 'shared')
Note the use of `short_path` instead of `%{output}` so it doesn't show `bazel-lib/darwin .../` at the start. The second commit changes the copy_file/directory to also use `short_path` for that reason.
Unlike copy_file/directory this PR makes copy_to_directory show the destination, not the source of the copied files because there might be many. We could show the target name, either instead of or in addition to the destination, but I figured the destination is decent?
=> fix: show directory being copied to in copy_to_directory progress message

docs/paths.md, lib/paths.bzl, lib/private/paths.bzl, lib/tests/paths_test.bzl
`to_manifest_path` was what we've always used in the past but Bazel has now added an `$(rlocationpath)` helper so I think it is preferable to switch over to that naming.
`to_repository_relative_path ` I think is more descriptive than `to_workspace_path` which seems ambiguous as to whether or not it will contain an `external/` segment for external repositories.
=> feat: add to_rlocation_path and to_repository_relative_path functions to paths.bzl

tools/common/file.go
On windows, I was receiving this error from rules_js from my build (I think using the npm_package rule):
```
2023/02/07 11:01:59 lstat bazel-out/x64_windows-fastbuild/bin/packages/wnd-shared-react-config/node_modules/@babel/plugin-proposal-object-rest-spread failed: CreateFile bazel-out/x64_windows-fastbuild/bin/packages/wnd-shared-react-config/node_modules/@babel/C:\tmp\hlntwacp\execroot\_main\bazel-out\x64_windows-fastbuild\bin\node_modules\.aspect_rules_js\@babel+plugin-proposal-object-rest-spread@7.17.3_@babel+core@7.20.12\node_modules\@babel\plugin-proposal-object-rest-spread: The filename, directory name, or volume label syntax is incorrect.
```
Turns out that `path.IsAbs` does not work on Windows, but `filepath.IsAbs` does so it was incorrectly determining absolute paths as …
=> Fix Realpath relying on path.IsAbs which does not work on windows

lib/private/write_source_file.bzl
Within `write_source_file()`, an incorrect `find` argument is being used on MacOS to iterate over the copied files. Instead of `find -type f`, it is using `find -type file`, which produces an error:
```
find: Must separate multiple arguments to -type using: ','
```
=> fix: incorrect 'find -type' argument used on MacOS

docs/docs.md, e2e/bzlmod/BUILD.bazel, e2e/bzlmod/MODULE.bazel, lib/extensions.bzl, lib/private/docs.bzl
In support of https://github.com/aspect-build/rules_js/issues/644
=> Changes needed for rules_js bzlmod support

.aspect/bazelrc/ci.bazelrc, .aspect/bazelrc/correctness.bazelrc, e2e/bzlmod/.aspect/bazelrc/correctness.bazelrc, e2e/bzlmod_write_source_files_external/.aspect/bazelrc/correctness.bazelrc, e2e/copy_to_directory/.aspect/bazelrc/correctness.bazelrc, e2e/workspace/.aspect/bazelrc/correctness.bazelrc, lib/tests/bazelrc_presets/all/ci.bazelrc, lib/tests/bazelrc_presets/all/correctness.bazelrc
We have observed that this settings leads to WARNINGS in npm package directory artifacts in the symlinked node_modules output tree created by rules_js for some npm packages.
For example,
```
WARNING: /private/tmp/f2/execroot/__main__/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/anymatch@3.1.3/node_modules/anymatch/LICENSE was modified during execution
WARNING: /private/tmp/f2/execroot/__main__/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@ampproject+remapping@2.1.2/node_modules/@ampproject/remapping/LICENSE was modified during execution
WARNING: /private/tmp/f2/execroot/__main__/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/@esbuild+darwin-x64@0.17.8/node_modules/@esbuild/darwin-x64/bin/esbuild was modified during execution
WARNING: …
```
=> fix: remove --experimental_guard_against_concurrent_changes from recommended correctness settings

README.md
Similar to https://github.com/bazel-contrib/rules-template/pull/52
=> docs: include from-HEAD install

.aspect/bazelrc/convenience.bazelrc, .aspect/bazelrc/correctness.bazelrc, .aspect/bazelrc/performance.bazelrc, e2e/bzlmod/.aspect/bazelrc/convenience.bazelrc, e2e/bzlmod/.aspect/bazelrc/correctness.bazelrc, e2e/bzlmod/.aspect/bazelrc/performance.bazelrc, e2e/bzlmod_write_source_files_external/.aspect/bazelrc/convenience.bazelrc, e2e/bzlmod_write_source_files_external/.aspect/bazelrc/correctness.bazelrc, e2e/bzlmod_write_source_files_external/.aspect/bazelrc/performance.bazelrc, e2e/copy_to_directory/.aspect/bazelrc/convenience.bazelrc, e2e/copy_to_directory/.aspect/bazelrc/correctness.bazelrc, e2e/copy_to_directory/.aspect/bazelrc/performance.bazelrc, e2e/workspace/.aspect/bazelrc/convenience.bazelrc, e2e/workspace/.aspect/bazelrc/correctness.bazelrc, e2e/workspace/.aspect/bazelrc/performance.bazelrc, lib/tests/bazelrc_presets/all/convenience.bazelrc, lib/tests/bazelrc_presets/all/correctness.bazelrc, lib/tests/bazelrc_presets/all/performance.bazelrc
From https://bazel.build/run/bazelrc#option-defaults
"""
The inheritance (specificity) graph is:
- Every command inherits from common
- The following commands inherit from (and are more specific than) build: test, run, clean, mobile-install, info, print_action, config, cquery, and aquery
- coverage inherits from test
"""
=> Presets cleanup

docs/utils.md, lib/private/utils.bzl, lib/tests/utils_test.bzl, lib/utils.bzl
Addresses TODO in rules_js: https://github.com/aspect-build/rules_js/blob/c3682586eff8c1b8e7ba91484a16df2be1729b5f/js/private/js_binary.bzl#L251
This can get removed in the future once Bazel 5 is EOL
=> feat: add consistent_label_str utility to generate consistent label strings for all Bazel versions

docs/stamping.md, lib/stamping.bzl
Previous target was deleted or renamed. Now use a permalink.
=> Update link to example from angular

.github/workflows/ci.yaml, e2e/coreutils/WORKSPACE
`aspect_bazel_lib_dependencies()` already makes the call implicitly
=> chore: remove unnecessary call to register_coreutils_toolchains() in e2e/coreutils

lib/BUILD.bazel, lib/private/docs.bzl
We've been making these exceptions in downstream repos
=> fix: disable stardoc under bzlmod and windows by default

lib/private/write_source_file.bzl
The `_is_file_missing()` function uses a glob to determine if a file is missing. However, it has `allow_empty = False`, which
means an error will occur if an empty directory is searched.
How has this been tested?
If part of the test plan included local testing, please provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
Using `write_source_file()` with an empty directory results in the following erro:
```
Traceback (most recent call last):
File "/Users/alister/example/BUILD.bazel", line 22, column 17, in <toplevel>
example(
File "/Users/alister/example/rules.bzl", line 595, column 22, in example
write_source_file(
File "/private/var/tmp/_bazel_alister/fb38e376d8efddf3cdb91fd1e4a65c39/external/aspect_bazel_lib/lib/private/write_source_ …
```
=> Correctly handle empty directory when checking for missing file

.bcr/config.yml, .github/workflows/release.yml
We want to cleanup our GitHub tokens, and this repo is different from all others by historical accident.
=> chore: use config.yml to indicate releaser

docs/jq.md, docs/stamping.md, lib/jq.bzl
Got a question on Bazel slack, this would have helped answer
**Type of change**
Documentation (updates to documentation or READMEs)
**Test plan**
Edited a rule under lib/tests/jq to make sure the new example does what I expect
=> docs(jq): document empty srcs

lib/private/copy_directory_toolchain.bzl, lib/private/copy_to_directory_toolchain.bzl
There shouldn't be any changes in the implementations of the golang binaries. Just bumping the version here since its an old one now. One day we'll include this in the release process.
---
=> chore: update copy directory golang binary release versions to use

docs/repositories.md, lib/private/yq_toolchain.bzl, lib/tests/yq/BUILD.bazel
The new version of yq is quite breaking, as it requires '-oj -r' for continued operation in rules_oci. We can do a default version flip later when more downstream projects are compatible.
---
Anyone relying on the new version being the default will have to opt-in. This has been live only four days so I think that's okay. I'll yank the prior release from BCR.
None
=> fix(yq): restore default version, reverting #405

lib/private/glob_match.bzl, lib/tests/glob_match_test.bzl
Prefactor to https://github.com/aspect-build/bazel-lib/issues/419
To add more test coverage and cleanup to keep the actual fix minimal.
---
=> refactor: cleanup glob implementation, add tests

lib/private/glob_match.bzl, lib/tests/glob_match_test.bzl
This is basically a rewrite that @thesayyn and I did using the [go doublestar](https://github.com/bmatcuk/doublestar/blob/465a339d8daa03b8620e49b8ae541f71651426ad/match.go#L74) implementation as a guide. Probably not worth looking at the diff in the second commit and just looking at the code.
- Performance (a code change that improves performance)
=> fix: rewrite glob implementation to follow standard glob specs

tools/BUILD.bazel, tools/expand_template/BUILD.bazel, tools/expand_template/main.go, tools/expand_template/mirror_release.sh
=> feat: introduce expand_template tool

.github/workflows/ci.yaml
The version was not updated from 5.4.0 to 5.4.1 in the windows exclusions.
=> chore: disable bazel 5 tests on windows

docs/yq.md, lib/private/BUILD.bazel, lib/private/docs/BUILD.bazel, lib/private/parse_status_file.yq, lib/private/yq.bzl, lib/tests/yq/BUILD.bazel, lib/yq.bzl
Fixes #223
---
```
Support stamping in yq rules
```
=> feat: yq supports stamping

lib/private/parse_status_file.yq
Fixes d79f4d4
Fixes #463
This is required since versions of yq older than 4.30.3 do not parse "\n" correctly. See https://github.com/mikefarah/yq/issues/1430 and https://github.com/mikefarah/yq/commit/e02bb7194897edb916a6787fb8f8e5a7f432dd94
---
1. Build any yq rule: `bazel build //lib/tests/yq:stamped`
2. Look at the processed stamping yaml: `cat bazel-bin/lib/tests/yq/_stamped_stamp.yaml`
Without this fix, the file only contains the first item of `bazel-out/stable-status.txt` and `bazel-out/volatile-status.txt` respectively. With the fix, every item appears in the yaml.
=> Use actual newline (instead of "\n") to split strings in yq rule

.bazeliskrc
Also for verifying the 5.6.0-rc8 Workflows release on GCP
=> chore: update to Aspect CLI 5.5.4

.circleci/config.yml
Copied from aspect-cli https://github.com/aspect-build/aspect-cli/blob/9fbad40204fe67a6fe1ef3973ec364aadbb274a2/.circleci/config.yml
---
CI on this PR
=> chore: setup CircleCI for Workflows

lib/private/docs.bzl
Fixes `update_docs` `existing_rules` logic with stardoc 0.6.0 and Bazel 7 by making it independent of the name of the internal rules instantiated by the `stardoc` macro.
Bug fix
Update stardoc to 0.6.0 and run with USE_BAZEL_VERSION=last_green
=> Fix `update_docs` with stardoc 0.6.0 and Bazel 7

.aspect/workflows/README.md, .aspect/workflows/terraform/.terraform.lock.hcl, .aspect/workflows/terraform/README.md, .aspect/workflows/terraform/main.tf, .aspect/workflows/terraform/vpc.tf, .aspect/workflows/terraform/workflows.tf, .circleci/config.yml, .gitignore
Switch over the a new deployment of Aspect Workflows on GCP that targets CircleCI only and land the terraform here so it serves as a live example of the full GCP + CircleCI Workflows configuration.
---
=> chore: add Aspect Workflows CI (on GCP + CircleCI)

lib/private/jq_toolchain.bzl
bazel-lib receives a number of issues regarding a linux-arm64 toolchain for `jq`. Add a comment here with the reasoning and pointer to the discussion issue.
---
=> docs: add comment regarding linux-arm64 JQ toolchain

.github/workflows/ci.bazelrc, .github/workflows/ci.yaml
Our Engflow cluster seems to be down.
---
=> chore: Switch to buildbuddy for RBE

.github/workflows/ci.bazelrc, lib/private/copy_common.bzl
It causes warnings like https://github.com/bazelbuild/bazel/blob/753cd459e49d1ffae1420bf5d46db228449299c6/src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java#L514 and also makes toolchain selection broken for host!=exec
Fixes #466
=> refactor: reduce execution requirements for copy

lib/private/yq.bzl, lib/tests/yq/BUILD.bazel
we have a number of files in our repository that are yaml, despite not having a .yaml suffix in their filename, and this filter prevents us from using the yq rule on them.
---
=> yq: allow any filename in srcs

.github/workflows/release_prep.sh, MODULE.bazel
This means we won't need a module_dot_bazel.patch file on BCR anymore.
=> chore: pull in https://github.com/bazel-contrib/rules-template/pull/93

MODULE.bazel
This was exposed by the BCR PR
=> fix: strip 'v' prefix from tag when setting module version

MODULE.bazel
This evaluates the same way, but tricks the parser in Publish-to-BCR app into skipping any replacements
=> refactor: invert the conditional for setting version

tools/expand_template/main.go
We used hexadecimal where we meant to use octal.
0x666 in binary is 11001100110 but 0666 is 110110110 (9 digits as expected)
so this was producing an output like
---xr--r-- 1 108 114 206 Sep  6 20:55 bazel-out/k8-opt/bin/stamped_labels.txt
we could fix both to explicit octal notation `0o666` and `0o777` but that's not what any of the "How to set permissions in Go" examples do. 
> An optional prefix sets a non-decimal base: 0b or 0B for binary, 0, 0o, or 0O for octal, and 0x or 0X for hexadecimal.
---
None, just visual inspection and reasoning
=> fix(expand_template): correct output permissions

.aspect/bazelrc/correctness.bazelrc, e2e/smoke/.aspect/bazelrc/correctness.bazelrc, lib/private/utils.bzl, lib/tests/bazelrc_presets/all/correctness.bazelrc
This is a good flag to enable by default because it prevents a common mistake and usually is what users expect.
---
- When updating their bazelrc to include this, some users may need to fix broken BUILD files or specify `allow_empty=True` when they were intentionally relying on the previous behavior.
Not sure this applies here.
=> docs: Add --incompatible_disallow_empty_glob to correctness.bazelrc

docs/jq.md, docs/repositories.md, lib/jq.bzl, lib/private/jq.bzl, lib/private/jq_toolchain.bzl, lib/tests/jq/BUILD.bazel
Fixes https://github.com/aspect-build/bazel-lib/issues/268
- Jq 1.7 is now supported which has a wider selection of platform binaries
- BREAKING: jq stamp variables are now of the form `$stamp[0].MY_VARIABLE` rather than `$stamp.MY_VARIABLE`.
=> feat: support jq 1.7 toolchain

BUILD.bazel, README.md, docs/BUILD.bazel, docs/lists.md, lib/BUILD.bazel, lib/lists.bzl, lib/private/docs/BUILD.bazel, lib/private/lists.bzl, lib/tests/BUILD.bazel, lib/tests/bazelrc_presets/all/BUILD.bazel, lib/tests/lists_test.bzl, tools/BUILD.bazel
This adds functions to work with lists from [bzlparty/lib_common](https://github.com/bzlparty/lib_common/blob/main/defs.bzl) as discussed in #495.
I removed the `occurs` functions, this is not needed because of the `in`-operator.
Please let me know if I should add more tests/documentation.
=> feat: add list utils

tools/copy_to_directory/main.go
Refs #359.
This allows `copy_to_directory` to be run in an external workspace and include files from that workspace automatically once the `copy_to_directory` rule is updated. The rule update needs to be separated from the tool update because the tool is pre-built and vendored rather than built at HEAD.
---
This was split off from https://github.com/aspect-build/bazel-lib/pull/360 in order to land the Go changes first and release a new version of the tool.
The new workspace name argument needs to be optional to avoid breaking the `copy_to_directory` rule. Once the rule is updated and released, we should consider making this argument required if the tool is not used elsewhere.
I didn't see any direct tests or documentation of the tool itself, so I left those for …
=> feat: update `copy_to_directory` tool to accept the name of its workspace and automatically include files from it

e2e/copy_to_directory/BUILD.bazel, e2e/smoke/BUILD.bazel, lib/private/diff_test.bzl, lib/private/diff_test_tmpl.sh, lib/tests/copy_directory_bin_action/BUILD.bazel, lib/tests/copy_to_directory_bin_action/BUILD.bazel, lib/tests/write_source_files/BUILD.bazel
Allows `diff_test` to run against source files on RBE.
---
Run against RBE cluster via patch.
=> fix: lookup source files from execroot when running diff_test on RBE

lib/private/write_source_file.bzl, lib/tests/write_source_files/build_files_in_outs/BUILD.bazel, lib/tests/write_source_files/build_files_in_outs/expected_out/BUILD, lib/tests/write_source_files/build_files_in_outs/expected_out/other.txt
Handles the case in `write_source_file` where the generated output directory contains `BUILD` files, which can not be globbed through, resulting in incorrect failure states for missing output files.
Closes #536
---
Handle `BUILD` files in the output of `write_source_file`
=> fix: allow for BUILD files in outputs of write_source_file

CONTRIBUTING.md
ensure developers have the right version to run all used hooks.
I was running into an error when trying to commit after the latest changes to [`.pre-commit-config.yaml`](https://github.com/aspect-build/bazel-lib/pull/532/commits/de0b477a0b27779b8245adfd0e30683bf9ffbdab), so I thought it might be useful to document the minimum version of `pre-commit` needed to ensure all hooks fired properly.
BTW, I had version v.3.1.0 installed and could not handle the `pre-push` hook
---
=> docs: add minimum pre-commit version

.bcr/patches/go_dev_dep.patch, .github/workflows/ci.yaml, MODULE.bazel
This ensures if a bzlmod user were to fetch bazel-lib with a SHA or a `git_repository`, they don't need to patch our repo (similar to how CI was doing it) in order to build the tools/ from head
=> chore: rules_go is a non-dev dep at HEAD

.aspect/workflows/terraform/main.tf, .aspect/workflows/terraform/vpc.tf, .aspect/workflows/terraform/workflows.tf, .circleci/config.yml
Also switch to using local vars for the `project` and `region` instead of a global provider so we assert that the `project` and `region` passed to the Workflows module is routed to all GCP resources.
=> chore: upgrade to Aspect Workflows 5.8.0-rc9

.aspect/bazelrc/correctness.bazelrc, lib/tests/bazelrc_presets/all/correctness.bazelrc
So that combined coverage reports make sense when build without the bytes is enabled.
- `--experimental_fetch_all_coverage_outputs` is now enabled in the correctness bazelrc presets
=> feat(presets): always fetch all coverage files on coverage runs

README.md, docs/expand_make_vars.md, lib/expand_make_vars.bzl, lib/tests/BUILD.bazel, lib/tests/expand_template/BUILD.bazel
- The import for `expand_template` has moved from `@aspect_bazel_lib//lib:expand_make_vars.bzl` to `@aspect_bazel_lib//lib:expand_template.bzl`.
=> chore: remove expand_template re-export

.github/workflows/ci.yaml, .gitignore, lib/private/tar.bzl
Seeing what CI thinks, I didn't see why we need the empty line at the end of the file
- Style (white-space, formatting, etc...)
**- Performance (a code change that improves performance)**
**- Covered by existing test cases**
- Manual testing; …
=> Avoid expanding mtree spec during analysis phase

.github/workflows/ci.yaml, MODULE.bazel
Bazel 5 is no longer officially supported by bazel-lib starting with 2.0.
=> chore: drop Bazel 5 support for 2.0

docs/paths.md, lib/BUILD.bazel, lib/paths.bzl, lib/private/copy_to_directory.bzl, lib/private/paths.bzl, lib/tests/paths_test.bzl, lib/windows_utils.bzl
Removes deprecated `to_workspace_path` and `to_manifest_path`. These functions were renamed to `to_repository_relative_path` and `to_rlocation_path` for clarity. The old names were kept around for backward compat in 1.x. This was a planned breaking change for the 2.0 release.
BREAKING CHANGES
- `to_workspace_path` helper function is removed from `paths`. Use `paths.to_repository_relative_path` instead.
- `to_manifest_path` helper function is removed from `paths`. Use `paths.to_rlocation_path` instead.
=> refactor: remove to_workspace_path and to_manifest_path from paths

.github/workflows/ci.bazelrc, lib/private/copy_common.bzl
Reverts aspect-build/bazel-lib#506
This made builds much slower for many users (e.g. rules_js copying npm dependencies) while not actually solving #466.
Proper solution will be a command-line flag that turns off our automatic execution requirements additions.
=> Revert "refactor: reduce execution requirements for copy"

MODULE.bazel
Also register them in the correct order, matching how WORKSPACE works
=> chore: fix tar_toolchain naming

.bazeliskrc, docs/copy_directory.md, docs/copy_file.md, docs/copy_to_directory.md, lib/BUILD.bazel, lib/copy_directory.bzl, lib/copy_file.bzl, lib/copy_to_directory.bzl, lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl
Alternative to #605
Fixes #604
Fixes #466
---
If you rely on Remote Execution and Build-without-the-bytes, you should add to your `.bazelrc`:
(with Bazel 6.4 or greater)
`common --@aspect_bazel_lib//lib:copy_use_local_execution=false`
or with Bazel 6.3 or earlier:
```
build --@aspect_bazel_lib//lib:copy_use_local_execution=false
fetch --@aspect_bazel_lib//lib:copy_use_local_execution=false
query --@aspect_bazel_lib//lib:copy_use_local_execution=false
```
Run aquery locally:
```
$ bazel aquery lib/tests/copy_file/...
action 'Copying file lib/tests/copy_file/file1'
Mnemonic: …
```
=> feat: expose a config_setting for copy execution_requirements

lib/private/repo_utils.bzl
HOMEPATH isn't always set. For example https://buildkite.com/bazel/bazel-bazel-examples/builds/2163#018b1a9d-0127-461f-8200-e89894397f35 USERPROFILE seems more widely documented as being the equivalent of HOME
---
Will verify downstream in a rules_oci usage
=> fix: windows home directory

.bcr/patches/go_dev_dep.patch, .github/workflows/release_prep.sh, MODULE.bazel, WORKSPACE, docs/jq.md, docs/repositories.md, docs/yq.md, e2e/copy_to_directory/MODULE.bazel, e2e/copy_to_directory/WORKSPACE, e2e/coreutils/MODULE.bazel, e2e/coreutils/WORKSPACE, e2e/smoke/WORKSPACE, lib/extensions.bzl, lib/jq.bzl, lib/private/extension_utils.bzl, lib/repositories.bzl, lib/yq.bzl
Stop automatically registering all of the toolchains in bazel-lib for WORKSPACE users. Make it easier to override toolchain versions under bzlmod.
Closes https://github.com/aspect-build/bazel-lib/issues/593.
* BREAKING: Toolchains are no longer automatically registered for WORKSPACE users. Users must call the `aspect_bazel_lib_register_toolchains` macro or call the `register_xyz_toolchain` macros individually. See [Release](https://github.com/aspect-build/bazel-lib/releases) for snippets.
* BREAKING: The host …
=> refactor: rework toolchain registration for WORKSPACE and bzlmod users

.bazeliskrc, lib/private/tar.bzl
Also restore the .bazeliskrc file I accidentally removed in 4bfe55711aaf64c724cd353c00459b9132d6e2bf
=> refactor: use _mtree_line helper

.github/workflows/release.yml
Since we stopped `--stamp`ing our releases, this check can never fail.
=> chore: remove useless check for stamped binary

.aspect/bazelrc/bazel5.bazelrc, docs/bazelrc_presets.md, lib/bazelrc_presets.bzl, lib/tests/bazelrc_presets/all/bazel5.bazelrc, lib/tests/bazelrc_presets/subset/BUILD.bazel, lib/tests/bazelrc_presets/subset/bazel5.bazelrc, lib/tests/bazelrc_presets/subset/convenience.bazelrc
Because bazel-lib 2.0 has a minimum Bazel compatibility set to 6.0.0.
=> chore: remove bazel5 presets

lib/private/write_source_file.bzl
---
We are past Bazel 4.x LTS. `lib/transitions.bzl` is already using merge_all.
=> Unconditionally use runfiles.merge_all in write_source_file

.circleci/config.yml
The continuation orb is a dep of the aspect-workflows orb and doesn't need to be explicitly specified
=> chore: tweak CCI config yaml

.aspect/bazelrc/performance.bazelrc, lib/private/copy_common.bzl, lib/tests/bazelrc_presets/all/performance.bazelrc, lib/tests/copy_to_directory_bin_action/BUILD.bazel
With "build without the bytes" working correctly and default in Bazel 7, our copy execution requirements should allow caching so that it works with this mode out of the box.
We should also not be opinionated about remote execution since with "build without the bytes", if you're copying all generated files around then it may be more efficient to do it on a remote executor. The subset of users that use remote execution can easily set custom execution requirements for the Mnenomic if desired.
---
- Performance (a code change that improves performance)
=> fix: fix execution requirements for 'build without the bytes'

.bazeliskrc, docs/copy_directory.md, docs/copy_file.md, docs/copy_to_directory.md, lib/BUILD.bazel, lib/copy_directory.bzl, lib/copy_file.bzl, lib/copy_to_directory.bzl, lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl
Reverts #606.
Feature added in #606 is no longer necessary after #639.
=> Revert: feat: expose a config_setting for copy execution_requirements (#606)

.bazeliskrc, .bcr/presubmit.yml, .github/workflows/ci.yaml, e2e/copy_to_directory/.bazeliskrc, e2e/coreutils/.bazeliskrc, e2e/external_copy_to_directory/.bazeliskrc, e2e/smoke/.bazeliskrc, e2e/write_source_files/.bazeliskrc
Windows CI is currently red at HEAD since Aspect CLI does not currently ship with Windows binaries: https://github.com/aspect-build/bazel-lib/actions/runs/6749471057/job/18349889696
=> chore: green up Windows CI

.github/workflows/ci.yaml, e2e/copy_to_directory/.bazeliskrc, e2e/coreutils/.bazeliskrc, e2e/external_copy_to_directory/.bazeliskrc, e2e/smoke/.bazeliskrc, e2e/write_source_files/.bazeliskrc, lib/private/copy_file.bzl, lib/private/copy_to_bin.bzl
Use the coreutils toolchain rather than bash/batch scripts to perform the copy.
- Refactor (a code change that neither fixes a bug or adds a new feature)**
Might require toolchain registration where previously it wasn't needed, if users did their own toolchain registration instead of calling `aspect_bazel_lib_register_toolchains` as the docs recommend
=> Use coreutils toolchain for copy_file action

.bcr/presubmit.yml, .gitattributes
Regressed in https://github.com/aspect-build/bazel-lib/pull/622. The addition of e2e/smoke/.bazeliskrc causes the BCR ci to fail. It seems to have difficulty loading the root bazelrc from this symlinked file under Windows. The solution here is to just leave it out of the release archive. The purpose of the bazeliskrc file here is to use the Aspect CLI on our own ci, but we don't need to use it on the BCR.
=> fix: exclude bazeliskrc from smoke test

.bcr/patches/go_dev_dep.patch, MODULE.bazel
Cherry pick 4a4dafa6e89dd1f856fc69ef64cfc4ff11dd4eee into 1.x. It's needed for https://github.com/aspect-build/bazel-lib/pull/659 to work.
=> Fix bzlmod (#600)

docs/copy_file.md, docs/copy_to_bin.md, lib/copy_file.bzl, lib/copy_to_bin.bzl, lib/private/copy_file.bzl, lib/private/copy_to_bin.bzl, lib/private/extension_utils.bzl, lib/repositories.bzl
For downstream rulesets to use bazel-lib 1.x and 2.x, some additions/fixes need to be included in the next 2.0 release. These include:
* copy action toolchain declarations
* toolchains module extension fix
- New feature or functionality (change which adds functionality
Manual testing against against rules_js and rules_ts overriden to point to this PR.
* https://github.com/aspect-build/rules_js/pull/1356
* https://github.com/aspect-build/rules_ts/pull/485
=> feat: expose toolchains used for copy actions

MODULE.bazel, docs/copy_file.md, docs/copy_to_bin.md, lib/copy_file.bzl, lib/copy_to_bin.bzl, lib/extensions.bzl, lib/private/copy_file.bzl, lib/private/copy_to_bin.bzl, lib/private/extension_utils.bzl, lib/repositories.bzl
For downstream rulesets to use bazel-lib 1.x and 2.x, some features need to be added back to 1.x for a new release. These include:
* copy action toolchain declarations
* new host and toolchains module extensions
- New feature or functionality (change which adds functionality
Manual testing against against rules_js and rules_ts overriden to point to this PR.
* https://github.com/aspect-build/rules_js/pull/1355
* https://github.com/aspect-build/rules_ts/pull/484
=> feat: backport 2.x features for interoperability

tools/BUILD.bazel
The version is exposed in 2.x. Backporting it here so we can switch on it to support bazel-lib 1.x/2.x in downstream rulesets.
=> feat: give version.bzl public visibility

BUILD.bazel, tools/BUILD.bazel, tools/format/BUILD.bazel
Fixes #686.
This regressed when rules_lint was brought in for format.
---
Why wasn't this caught in CI and in bzlmod presumbit in #681 ?!?
=> fix: isolate rules_lint dev dependency usage into its own Bazel package

lib/BUILD.bazel, lib/tar.bzl, lib/tests/tar/BUILD.bazel, lib/tests/tar/asserts.bzl
Not sure if it's worth the time to add an analysis_test for something this simple.
=> fix(tar): propagate testonly attr to mtree_spec

MODULE.bazel, docs/BUILD.bazel, docs/bats.md, docs/repositories.md, e2e/smoke/BUILD.bazel, e2e/smoke/basic.bats, internal_deps.bzl, lib/BUILD.bazel, lib/bats.bzl, lib/extensions.bzl, lib/private/BUILD.bazel, lib/private/bats.bzl, lib/private/bats_toolchain.bzl, lib/repositories.bzl, lib/tests/bats/BUILD.bazel, lib/tests/bats/additional_lib.bats, lib/tests/bats/basic.bats, lib/tests/bats/bats-custom/BUILD.bazel, lib/tests/bats/bats-custom/load.bash, lib/tests/bats/env.bats, lib/tests/bats/env_expansion.bats
=> feat: implement bats test runner

.github/workflows/ci.yaml, .github/workflows/release.yml, BUILD.bazel, MODULE.bazel, WORKSPACE, internal_deps.bzl, lib/private/BUILD.bazel, lib/private/utils.bzl, lib/tests/BUILD.bazel, lib/tests/copy_to_directory_bin_action/BUILD.bazel
Bazel 7 final it out now. We can flip to testing Bazel 7 as primary & Bazel 6.4.0 as secondary in a follow-up PR.
=> chore: test against bazel 7.0.0

BUILD.bazel, docs/utils.md, lib/private/BUILD.bazel, lib/utils.bzl
In the future we should make detection of the Bazel version part of the public API of bazel_features and use that. 
Currently, however, the [bazel version comparison functions in bazel_features](https://github.com/bazel-contrib/bazel_features/blob/main/private/util.bzl) are private API so a change needs to be made there to make the public API. Also adding a new non-dev dep on bazel_features here would be breaking for WORKSPACE users which is undesirable atm.
---
=> feat: add is_bazel_7_or_greater utility function to public API

.aspect/bazelrc/javascript.bazelrc, lib/tests/bazelrc_presets/all/javascript.bazelrc, lib/tests/bazelrc_presets/subset/javascript.bazelrc
With https://github.com/aspect-build/rules_js/pull/1428, rules_js no longer requires runfiles.
---
=> refactor: remove --enable-runfiles from javascript recommended bazelrc settings

lib/tests/run_binary_expansions/expansions.sh
This test is failing locally on an M3 mac. Likely would fail on a linux arm64 as well.
```
==================== Test output for //lib/tests/run_binary_expansions:expansions_golden_test:
1,2c1,2
< bazel-out/PLATFORM_arm64-opt/bin/lib/tests/run_binary_expansions/expansions_out
< bazel-out/PLATFORM_arm64-opt/bin/lib/tests/run_binary_expansions
---
> bazel-out/PLATFORM-opt/bin/lib/tests/run_binary_expansions/expansions_out
> bazel-out/PLATFORM-opt/bin/lib/tests/run_binary_expansions
5,6c5,6
< bazel-out/PLATFORM_arm64-opt/bin/lib/tests/run_binary_expansions/src_1
< bazel-out/PLATFORM_arm64-opt/bin/lib/tests/run_binary_expansions/src_1
---
> bazel-out/PLATFORM-opt/bin/lib/tests/run_binary_expansions/src_1
> bazel-out/PLATFORM-opt/bin/lib/tests/run_binary_expansions/src_1
9,10c9,10
< …
```
=> chore: fix failing test on arm64 machines

docs/write_source_files.md, lib/private/write_source_file.bzl, lib/tests/BUILD.bazel, lib/tests/a.js, lib/tests/write_source_files/BUILD.bazel, lib/tests/write_source_files/subpkg/BUILD.bazel, lib/tests/write_source_files/subpkg/a.js, lib/tests/write_source_files/write_source_file_test.bzl, lib/write_source_files.bzl
We've received requests for this feature a few times now with the latest one being here https://bazelbuild.slack.com/archives/C04281DTLH0/p1704883631739649.
The glob trick to check that the out file exists must be disabled by setting `check_that_out_file(s)_exists` to `False` when writing to a different Bazel package. The trick doesn't work unless the out file is in the same Bazel package (glob's don't traverse into sub packages and can't look into sibling or parent packages).
write_source_files(s) can now write source files to Bazel packages outside of the target's package when you set `check_that_out_file(s)_exists` to False.
- New test …
=> feat: allow write_source_file(s) to write source files to bazel packages outside of the target's package

.aspect/workflows/terraform/workflows.tf
e2-small was pushing it for the number of services running on the node
=> chore: bump to e2-medium k8s nodes

docs/BUILD.bazel, lib/private/docs.bzl
Discovered this bug while working on https://github.com/aspect-build/rules_jasmine/pull/119.
---
=> fix: merge user tags in stardoc_with_diff_test

.aspect/bazelrc/ci.bazelrc, lib/tests/bazelrc_presets/all/ci.bazelrc
In practice we've disabled this setting at some clients, because there's not a surrounding workflow to find these targets are being silently dropped from CI, nor run them on another schedule.
We can re-introduce something better when we add Test Selection to Aspect Workflows.
---
We no longer recommend filtering test targets by timeout on CI for all cases. Some organizations may still want to restore this setting locally as a matter of policy, but you need to do *something* with the filtered test targets to keep them green.
=> presets: remove eternal test_timeout_filtering

lib/private/run_binary.bzl
`ctx.actions.run(executable = ...)` is sufficient to include the runfiles in the action inputs. (More generally, for tools other than the executable,`ctx.resolve_tools` is discouraged in favor of `ctx.actions.run(tools = ...)`.)
=> Remove unnecessary ctx.resolve_tools.

docs/jq.md, lib/jq.bzl, lib/private/BUILD.bazel, lib/private/jq.bzl, lib/tests/jq/BUILD.bazel
This teaches the jq rule about a `data` attribute and adds conditional support to do bazel location expansion. The expansion is disabled by default because it likely would cause compat concerns (since jq can take arbitrary text as input args).
jq now supports data dependencies and optional location expansion on the args attr
=> jq: add data file and location expansion support

docs/lists.md, lib/lists.bzl, lib/private/lists.bzl, lib/tests/lists_test.bzl
Add a function that returns a list with unique items. I find this function quite useful and use it here and there. What do you think?
=> feat(list): add `unique` function

lib/private/tar_toolchain.bzl
See https://ubuntu.com/security/notices/USN-6658-1
Bumps the package fetched.
=> chore: bump libxml2 deb to USN-6658-1

lib/tar.bzl
```
Allows users to type without explicitly setting srcs to []
tar(
name = "tmp",
mtree = ["..."]
)
```
=> fix: tar#srcs is optional

docs/tar.md, lib/private/tar.bzl, lib/tests/tar/BUILD.bazel
#785 fixed the weird issue when no srcs were passed but didn't actually made the srcs optional.
=> fix: srcs is not mandatory

.aspect/workflows/config.yaml, .aspect/workflows/deps.bzl, .circleci/config.yml
Also upgrade to Workflows v5.9.23 which adds support for artifact_paths to CircleCI
=> chore: stash output of vmstat in artifacts

docs/BUILD.bazel, docs/resource_sets.md, lib/BUILD.bazel, lib/private/source_toolchains_repo.bzl, lib/resource_sets.bzl
This API is poorly designed and needs some help to let rule users pick a value in cases that they aren't also the rule author
Workaround for https://github.com/bazelbuild/bazel/issues/15187
---
I'm using it downstream in rules_ts.
=> feat: add a helper for rules to work with resource_sets

lib/private/write_source_file.bzl
We hit an issue recently where the `write_source_file` halted during the `cp` part of a `bazel run <write_source_file_target>` command, this can leave dirs/files copied to the workspace to be read-only, and a subsequent `bazel run <write_source_file_target>` will fail with permission-denied. This is our workaround to this.
Simpler case in point:
```
$ mkdir bar
$ touch bar/baz
$ chmod -w bar
$ rm -r bar
rm: bar/baz: Permission denied
```
Test locally by:
1. running a bazel run command
2. while it's in the `cp` phase, terminate it before the command completes
3. verify that subdirs in the destination folder are read-only (`dr-xr-xr-x`)
4. subsequent bazel run command fail with `Permission denied`
5. Repeat 1-4, but with this patch, subsequent bazel run command always succeeds.
=> clean rm of copied dirs and files

docs/utils.md, lib/utils.bzl
`//lib:utils.bzl` is the odd one out that fine grain re-exports. `//lib:repo_utils.bzl` exports `repo_utils` only and `//lib:platform_utils.bzl` exports `platform_utils` only. We missed our chance to remove the fine grained re-exports in bazel-lib 2.0 but no reason we can't stop the bleed of fine grained re-exports at this point.
---
=> feat: export utils from //lib:utils.bzl to match repo_utils and platform_utils

docs/transitions.md, lib/tests/transitions/BUILD.bazel, lib/tests/transitions/simple_test.go, lib/transitions.bzl
New feature or functionality (change which adds functionality)
Adding a test equiv. for `platform_transition_binary`. We find this very useful when we need to run tests targeting multiple platforms.
New test cases added
=> feat: add platform_transition_test

lib/private/tar_toolchain.bzl
Picks up fix for downstream rules_js issue https://github.com/aspect-build/rules_js/issues/1597.
---
=> chore: bump to bsdtar-prebuilt 3.7.2-1 binaries for linux and darwin

.github/workflows/conventional-commits.yml
We want contributors to follow the instructions in the PR template, and use conventional commits to indicate the type of the PR.
Note, this uses the amannn upstream to check the title. We could use aspect-forks instead to check the description as well: https://github.com/aspect-forks/action-semantic-pull-request/blob/main/src/validatePrDescription.js
---
will observe it running
=> ci: enforce PR titles are semantic

.aspect/bazelrc/javascript.bazelrc, lib/tests/bazelrc_presets/all/javascript.bazelrc, lib/tests/bazelrc_presets/subset/javascript.bazelrc
@jfirebaugh pointed out that we are missing this.
Tested downstream in rules_js:
```
bazel test //examples/js_binary:test_test --config=debug
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //examples/js_binary:test_test (0 packages loaded, 0 targets configured).
Debugger listening on ws://127.0.0.1:9229/385833a3-8f5e-437e-804d-a888a56bf7dd
For help, see: https://nodejs.org/en/docs/inspector
[1 / 2] Testing //examples/js_binary:test_test; 4s darwin-sandbox
```
=> chore: add bazel test support to javascript --config=debug preset

docs/tar.md, lib/private/BUILD.bazel, lib/private/modify_mtree.awk, lib/tar.bzl, lib/tests/tar/BUILD.bazel, lib/tests/tar/expected1.mtree, lib/tests/tar/expected2.mtree, lib/tests/tar/source-casync.mtree
The genrule we used was too complex to ask users to copy-paste it
This is a partial step to exposing a rules_pkg `pkg_tar` compatible API.
---
- Suggested release notes appear below: yes
The `tar` package now provides a new `mtree_mutate` macro which allows a more ergonomic equivalent of pkg_tar attributes like `strip_prefix`, `uid`, and more.
=> feat(tar): add ergonomic way to strip_prefix

MODULE.bazel
I don't know why Bazel did not complain that the toolchain wasn't registered. 
- Suggested release notes appear below: no
=> fix: register @zstd_toolchains//:all

tools/expand_template/main.go, tools/integrity.bzl
---
Bug fix (change which fixes an issue)
https://bazelbuild.slack.com/archives/C04281DTLH0/p1713216473704709
Follow-up from https://github.com/aspect-build/bazel-lib/pull/820
The old regex was including newlines when checking for the second value, so this switches it to only look for spaces/tabs instead
Updated link to new regex101 examples
=> fix: only check for blank space between status entries in expand_template

docs/repositories.md, lib/private/coreutils_toolchain.bzl, tools/coreutils_mirror_release.sh
Uutils has a musl release artifact for linux amd64 and linux arm64. <strike>In the future, it should probably also be possible to add a aarch64 musl toolchain. At the moment, this is not an upstream release artifact.
I'm in the process of [fixing this upstream](https://github.com/uutils/coreutils/issues/5690).</strike>
- Bug fix (fixes #701)
=> fix: coreutils toolchain: Use statically linked linux amd64 variant

.aspect/workflows/config.yaml, .circleci/config.yml
With Bazel 7, the `CC=/bin/false` no longer works with rules_go so the Workflows runners now have gcc on them.
=> ci: green up main

.bcr/patches/go_dev_dep.patch, MODULE.bazel, internal_deps.bzl, lib/repositories.bzl
Pre-factor from https://github.com/aspect-build/bazel-lib/pull/843
=> chore: bump buildifier, go and gazelle deps

.aspect/bazelrc/.gitignore, .aspect/workflows/config.yaml, .bazelrc, .circleci/config.yml, .github/workflows/ci.bazelrc, .github/workflows/ci.yaml, .github/workflows/release.yml, .gitignore, .pre-commit-config.yaml, WORKSPACE, e2e/copy_action/.bazelrc, e2e/copy_action/MODULE.bazel, e2e/copy_to_directory/.bazelrc, e2e/copy_to_directory/MODULE.bazel, e2e/coreutils/.bazelrc, e2e/coreutils/MODULE.bazel, e2e/external_copy_to_directory/.bazelrc, e2e/external_copy_to_directory/MODULE.bazel, e2e/smoke/.bazelrc, e2e/smoke/MODULE.bazel, e2e/write_source_files/.bazelrc, e2e/write_source_files/MODULE.bazel, tools/format/BUILD.bazel
Lots of cleanup of our CI and bazelrc patterns here. Aligns these patterns with our other rulesets. No functional changes.
=> chore: align ci patterns

MODULE.bazel
Put dev_dependencies where they belong
=> chore: tidy in MODULE.bazel file

lib/private/coreutils_toolchain.bzl
---
Ran `bazel run //:format` locally to completion
=> fix: coreutils download path for darwin_amd64

tools/common/file.go, tools/copy_directory/main.go, tools/copy_to_directory/main.go
Pre-factors for https://github.com/aspect-build/bazel-lib/pull/857.
---
CI
=> refactor: pre-factors for fix in copy_to_directory

tools/copy_to_directory/main.go
Allows for dangling symlinks inputs to be excluded before realpath is called on them.
---
CI
=> fix: exclude files in copy_to_directory before checking their realpath

lib/tests/run_binary/BUILD.bazel
In support of a Bazel Slack question on `location` of `run_binary` `out_dirs`: https://bazelbuild.slack.com/archives/C04281DTLH0/p1717607601723849?thread_ts=1717158361.547679&cid=C04281DTLH0.
---
=> test: add test / example of using rootpath on a run_binary directory output

lib/private/write_source_file.bzl, lib/tests/write_source_files/BUILD.bazel, lib/tests/write_source_files/hidden_dir/.hidden
Copy and manage hidden files starting with "." in write_source_files.
Previously these files were not supported if they were in the top level of the directory to copy.
Refs: #667 
---
- Suggested release notes appear below: no
- Manual testing: Used this lib version to copy a directory of generated files that included hidden files.
=> fix: Directory hidden files in write_source_file.

docs/stamping.md, lib/stamping.bzl
=> docs: add missing default stamp var

lib/private/tar_toolchain.bzl
---
- Suggested release notes appear below: yes
bsdtar is now version 3.7.4 and includes some improvements to how its compiled, see https://github.com/bazelbuild/bazel-central-registry/pull/1916
=> chore: upgrade bsdtar to 3.7.4

lib/private/copy_to_directory.bzl, lib/tests/copy_to_directory/BUILD.bazel
Requested by a Bazel support customer where a copy_to_directory target in their repo had no srcs. 
Remove an explicit fail check on empty srcs since outputting an empty directory is valid in Bazel and a valid use case for `copy_to_directory` rule.
---
=> fix: allow copy_to_directory to have an empty srcs list

docs/tar.md, lib/tar.bzl, lib/tests/tar/BUILD.bazel, lib/tests/tar/expected1.mtree
This was likely forgotten in #829 when making the parameters explicit during review.
---
- Searched for relevant documentation and updated as needed: yes (stardoc)
- Breaking change (forces users to change their own code or config): no (genrule does not have a package_dir argument)
- Suggested release notes appear below: no (suggest to use commit message / PR title)
=> fix(tar): expose package_dir argument in mtree_mutate

BUILD.bazel, lib/private/modify_mtree.awk, lib/private/tar.bzl, lib/tests/tar/BUILD.bazel, lib/tests/tar/expected13.mtree, lib/tests/tar/expected14.mtree
bsdtar's mtree format has a quirk wherein entries without "/" in their first word are treated as "relative" entries, and "relative" directories will cause tar to "change directory" into the declared directory entry. If such a directory is followed by a "relative" entry, then the file will be created within the directory, instead of at top-level as expected. To mitigate, we append a slash to top-level directory entries.
Fixes #851.
---
- New test cases added: `//:tar_test13`, `//lib/tests/tar:test14`
=> fix(tar): append slash to top-level directory mtree entries

lib/private/tar_toolchain.bzl
This fixes the dynamic lookup of zstd from the PATH. 
Fixes #877
=> chore(deps): update bsdtar prebuilt

docs/diff_test.md, docs/testing.md, lib/private/diff_test.bzl, lib/private/write_source_file.bzl, lib/testing.bzl, lib/tests/write_source_files/write_source_file_test.bzl
Currently, we are unable to run our `write_source_files` tests in our pre-upload checks, because we have `--test_size_filter=small`, and setting `size` will attempt to set it on both the run rule and the test rule, the former being invalid.
See [here](https://github.com/bazelbuild/bazel/issues/22355) for more details.
`bazel test //... --test_size_filters=small`
Before: 5 tests run
After: 152 tests run
=> fix: Set size to a default value as well as timeout.

.aspect/bazelrc/correctness.bazelrc, .pre-commit-config.yaml, README.md
---
A the typos pre-commit hook to automatically detect and mostly fix typos. Reading your documentation, I found one and wanted to provide a general solution. Follow up PRs can cleanup the excluded folders.
=> chore(typos): Add typos hook plus some fixes

docs/tar.md, lib/tar.bzl, lib/tests/tar/BUILD.bazel
Improve the content to make it easier to reference as examples of usage.
---
None; docs only
=> docs(tar): point to the tests as useful examples

deps.bzl
This got out of date due to a renovate dep bump. Guess we don't have a CI check for `bazel run //:gazelle_update_repos` yet here.
=> chore: bazel run //:gazelle_update_repos

tools/common/BUILD.bazel, tools/common/clonefile_darwin.go, tools/common/clonefile_stub.go, tools/common/copy.go
This can save time and disk-space when copying files around on the same device. File clones (aka reflinks) share backing disk blocks; they differ from hardlinks in that inodes are not shared and the contents are copy-on-write.
The Go standard library (as of v1.22) will arrange to do a similar thing for file copies on Linux (see: https://cs.opensource.google/go/go/+/refs/tags/go1.22.6:src/os/zero_copy_linux.go;l=53). Unfortunately, Mac OS' more limited API is less amenable to that form of transparent wrapping.
---
Manually confirmed that cloned files differ in inode but share backing blocks with a custom script ([gist](https://gist.github.com/plobsing/dc4456e1b461563a3a9e0e93673834b9)).
```
❯ bazel test lib/tests/copy_to_directory:all
[...]
hardlink …
```
=> perf: use darwin's clonefile syscall

MODULE.bazel
Commit 3c121a9cd9c665f3aca903c473ec91dc8af68721 broke E2E tests with the following error:
```
(23:31:56) ERROR: no such package '@@[unknown repo 'org_golang_x_sys' requested from @@aspect_bazel_lib~]//unix': The repository '@@[unknown repo 'org_golang_x_sys' requested from @@aspect_bazel_lib~]' could not be resolved: No repository visible as '@org_golang_x_sys' from repository '@@aspect_bazel_lib~'
```
The build worked when operating within the `aspect_bazel_lib` repo itself, but not when importing it with Bzlmod. This is because the `org_golang_x_sys` repo is imported indirectly by `rules_go`'s `go_rules_dependencies` macro in the `WORKSPACE` file, which is still active under bzlmod because there is no `WORKSPACE.bzlmod` file to suppress it.
---
Have confirmed that …
=> fix: add bzlmod use_repo of org_golang_x_sys

.aspect/bazelrc/bazel7.bazelrc, lib/tests/bazelrc_presets/all/bazel7.bazelrc
These are misinformed, the module resolver should be permitted to find an MVS solution
=> chore: turn off bzlmod misguided warning

e2e/smoke/BUILD.bazel, e2e/smoke/test_preserve_mtime.sh, tools/common/copy.go
and also
```
bazel run //:format -- e2e/smoke/test_preserve_mtime.sh tools/common/copy.go
```
=> chore: bazel run //:buildifier

docs/expand_make_vars.md, lib/expand_make_vars.bzl, lib/private/BUILD.bazel, lib/private/bats.bzl, lib/private/expand_locations.bzl, lib/private/expand_template.bzl, lib/private/jq.bzl, lib/private/params_file.bzl, lib/private/run_binary.bzl
`expand_locations` is marked DEPRECATED since it now just calls `ctx.expand_location(input, targets = targets)`. There was once a custom implementation but that was removed a while ago.
---
- Suggested release notes appear below: yes
`expand_locations` is marked DEPRECATED since it now just calls `ctx.expand_location(input, targets = targets)`. There was once a custom implementation but that was removed a while ago.
=> refactor: deprecated expand_locations which is just pass-through to ctx.expand_location()

lib/tests/base64_tests.bzl, lib/tests/lists_test.bzl, lib/tests/strings_tests.bzl
Resolves:
```
//lib/tests:base64_tests_test_0                                          PASSED in 1.3s
WARNING: //lib/tests:base64_tests_test_0: Test execution time (1.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//lib/tests:lists_tests_test_0                                           PASSED in 1.5s
WARNING: //lib/tests:lists_tests_test_0: Test execution time (1.5s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//lib/tests:lists_tests_test_1                                           PASSED in 1.6s
WARNING: //lib/tests:lists_tests_test_1: Test execution time (1.6s excluding execution overhead) outside of range for MODERATE tests. Consider setting …
```
=> chore: fixup test sizes to resolve warnings

docs/jq.md, docs/strings.md, lib/jq.bzl, lib/private/BUILD.bazel, lib/private/bats.bzl, lib/private/expand_template.bzl, lib/private/jq.bzl, lib/private/params_file.bzl, lib/private/run_binary.bzl, lib/private/strings.bzl, lib/strings.bzl, lib/tests/strings_tests.bzl
Fixes https://github.com/aspect-build/bazel-lib/issues/891 (requested by Bazel Open Source Support customer).
---
- Suggested release notes appear below: yes
New function `split_args` is added to the public API of `strings.bzl`.
This fix touches a number of different rules:
- `jq` rule expansions now include make vars and rule fixed to single quote args that contain spaces
- `expand_template` optimized to not to bother with pointless `.split(" ")` followed by `" ".join()`
- `bats_test` optimized to not to bother with pointless `.split(" ")` followed by `" ".join()`
- `params_file` rule fixed to correctly split args on quotes
- `run_binary` rule fixed to …
=> fix: correctly split quoted args

lib/tests/transitions/BUILD.bazel
=> chore: skip linux only tests on non-linux platforms

lib/tests/transitions/BUILD.bazel, shlib/tests/lib_tests/assertions_tests/BUILD.bazel
Resolves:
```
//lib/tests/transitions:test_go_binary_is_arm64                 (cached) PASSED in 0.1s
WARNING: //lib/tests/transitions:test_go_binary_is_arm64: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//lib/tests/transitions:test_go_binary_is_x86_64                (cached) PASSED in 0.2s
WARNING: //lib/tests/transitions:test_go_binary_is_x86_64: Test execution time (0.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//lib/tests/transitions:test_go_test_is_x86_64                  (cached) PASSED in 0.1s
WARNING: //lib/tests/transitions:test_go_test_is_x86_64: Test execution time (0.1s excluding execution overhead) …
```
=> chore: right size tests to supress bazel warning

lib/private/BUILD.bazel
Now that #915 landed we can remove this sadness.
---
=> chore: remove non-bzlmod dep on @internal_platforms_do_not_use//host:constraints.bzl now that root workspace is bzlmod-only

.aspect/workflows/bazelrc, .aspect/workflows/config.yaml, .circleci/config.yml
Enable Aspect Workflows RBE.
---
Observe build on CircleCi pipeline.
=> chore: use aspect workflows RBE

docs/repositories.md, lib/private/coreutils_toolchain.bzl
This release has an `aarch64-apple-darwin` binary, eliminating the need for a `version_override` hack to support that platform.
---
```
bazel test ...
cd e2e/smoke
bazel test ...
```
All previously passing tests still pass; `//lib/tests/transitions:transitioned_go_test_arm64` fails in the same way it had before (on a Darwin / ARM machine).
=> chore(deps): update coreutils to v0.0.27

docs/copy_directory.md, docs/copy_file.md, lib/copy_directory.bzl, lib/copy_file.bzl, lib/private/copy_common.bzl, lib/private/copy_directory.bzl, lib/private/copy_file.bzl, lib/private/copy_to_directory.bzl
The change to `progress_message` saves around 100ms of analysis time for my big repo. The rest of the changes are cleanups to reflect that we have long since diverged from skylib's implementation.
=> perf: Improve copy_file.bzl's progress_message and do some cleanup

.aspect/bazelrc/performance.bazelrc
Noticed this in https://github.com/EngFlow/bazel_invocation_analyzer/issues/107
---
Not sure. Maybe we should try enabling this flag at several client sites and see if it sticks.
=> feat: performance preset: nobuild_runfiles_links

.aspect/bazelrc/README.md, .aspect/bazelrc/bazel6.bazelrc, .aspect/bazelrc/correctness.bazelrc, .aspect/bazelrc/usage.md, .github/workflows/release_prep.sh, BUILD.bazel, README.md, docs/expand_template.md, docs/utils.md, go.mod, lib/private/copy_directory_toolchain.bzl, lib/private/copy_to_directory_toolchain.bzl, lib/private/expand_template.bzl, lib/private/expand_template_toolchain.bzl, lib/private/utils.bzl, lib/private/write_source_file.bzl, lib/private/yq_toolchain.bzl, lib/tests/bazelrc_presets/all/bazel6.bazelrc, lib/tests/bazelrc_presets/all/correctness.bazelrc, lib/tests/bazelrc_presets/all/write_aspect_bazelrc_presets.bzl, lib/tests/copy_to_directory/BUILD.bazel, lib/tests/copy_to_directory_bin_action/BUILD.bazel, lib/tests/transitions/BUILD.bazel, tools/common/BUILD.bazel, tools/copy_directory/BUILD.bazel, tools/copy_directory/main.go, tools/copy_to_directory/BUILD.bazel, tools/copy_to_directory/main.go, tools/expand_template/BUILD.bazel
This repository was donated to the Linux Foundation and is now in the bazel-contrib GH org.
Also remove mentions of Aspect from the README.
=> chore: update git urls

.aspect/bazelrc/performance.bazelrc
A user reported that this flag broke `coverage` because it makes assumptions about locating tools: https://github.com/bazelbuild/bazel/issues/20577
=> fix(presets): restore build runfile links for the 'coverage' command

.bcr/metadata.template.json
Required by a BCR presubmit check, which blocked the last two releases.
=> fix: update metadata.template.json for LF donation

lib/private/tar.bzl, lib/tests/tar/BUILD.bazel
Under bzlmod, repos have aliases in addition to their canonical names;
in order for lookups using these alias names to function properly,
a file name `_repo_mapping` is located in the root of the runfiles tree
and consulted to perform repo-name translation.
See: https://github.com/bazelbuild/proposals/blob/main/designs/2022-07-21-locating-runfiles-with-bzlmod.md
=> feat: support bzlmod runfiles lookups

docs/tar.md, lib/tar.bzl
With Bzlmod, every repo has its own namespace. Using Label() should make sure it uses the namespace of the .bzl file instead of the caller's one.
=> fix: unknown repo error with mtree_mutate and Bzlmod

lib/tests/transitions/BUILD.bazel, lib/transitions.bzl
The target platform of a test rule matters for the resolution of the execution platform of the test action, either via test toolchains or `--use_target_platform_for_tests`. With an outgoing transition, tests would run on the wrong platform in these cases, so use an incoming transition for the test rule.
=> fix: Use transitioned target platform for `platform_transition_test`

lib/private/tar_toolchain.bzl
Fixes tar extract regression in [2.8.0](https://github.com/bazel-contrib/bazel-lib/releases/tag/v2.9.0) due to bump to bsdtar-prebuilt 3.7.5 in https://github.com/bazel-contrib/bazel-lib/pull/940.
bsdtar-prebuilt 3.7.5 (which depends on libarchive 3.7.5) has a regression that showed up in testing of our internal silo repo when attempting to bump bazel-lib. previously working tests with tar extracts starting to fail with `invalid tar header`. I also tested with a bsdtar-prebuilt 3.7.7 release, built with libarchive 3.7.7 to see if there was a regression in libarchive 3.7.5 but also hit the same failure. Another possibility is BCR patches for libarchive 3.7.5 were copied over from 3.7.4 and they might not be correct.
In any case, to get back to a working version of tar in bazel-lib, this …
=> fix: go back to bsdtar-prebuilt 3.7.4 but with a release with a working windows binary

.aspect/bazelrc/bazel6.bazelrc, .aspect/bazelrc/correctness.bazelrc
It was also renamed from experimental_ to incompatible_, though surprisingly the original flag name is still permitted in Bazel 7 without errors.
Rename and default flip was in https://github.com/bazelbuild/bazel/commit/d0625f5b37e7cfe4ecfcff02b15f634c53d7440c
=> fix: allow_tags_propagation defaults true in 7

docs/tar.md, lib/tar.bzl
For now we will just warn people to do the right thing. 
See: https://github.com/bazel-contrib/bazel-lib/issues/783
=> docs: warn about gzip timestamps

lib/private/tar.bzl
This field is only present in Bazel versions v7.0 or later. An accommodation for its absence is required while v6.x versions are still supported by this library.
Fixes https://github.com/bazel-contrib/bazel-lib/issues/975
=> fix: access FilesToRunProvider.repo_mapping_manifest indirectly

lib/private/tar.bzl
Based on https://github.com/bazel-contrib/bazel-lib/pull/795#issuecomment-2492094147
=> fix(tar): handle directories with spaces in name

lib/private/bats.bzl
small addition to the bats test runner to drop junit-formatted output where bazel expects it
=> feat: bats_test: add junit report to test results

docs/jq.md, lib/jq.bzl
As seen here: https://github.com/bazel-contrib/bazel-lib/blob/31e6c76b7d2e91657913232ec33da6a8b6ace90b/lib/jq.bzl#L87
The docs show the incorrect escaping sequence.
=> docs: Update jq docs to show correct escaping

lib/private/tar.bzl
Small drive by fix while creating https://github.com/bazel-contrib/bazel-lib/pull/987. Many linters in different languages recommend not to use else after a return, see
- C++: https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html
- Python: https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-else-return.html or https://docs.astral.sh/ruff/rules/superfluous-else-return/
=> refactor: Fix no-else-after-return

lib/private/write_source_file.bzl
In write_source_file, the output file should honor the current umask when marking files as writable. Not doing so ends up in situations where the file is e.g. created as 664 when initially generated with `write_source_file` but then a git clone/checkout/subtree would create it as 644. This can cause confusion to the user, and might unnecessarily be treated as a file change by some tooling.
From `man 2 chmod`, describing `chmod [who]+[perm]`:
> If no value is supplied for [who], each permission bit specified in
> [perm], for which the corresponding bit in the file mode creation mask
> (see umask(2)) is clear, is set.
=> fix: honor umask in write_source_file

docs/tar.md, lib/private/tar.bzl, lib/tar.bzl
Maybe a naive approach since I don't know the lib very well. I found https://github.com/bazel-contrib/bazel-lib/blob/main/docs/tar.md#important-note and could not come up with any situation where a user does want to have a non-deterministic tarball.
Replace https://github.com/bazel-contrib/bazel-lib/pull/987
Closes #783
---
I was also thinking about adding an integration test for this such as building a tarball twice and make sure the second one is cached. Open for other suggestions though.
=> fix: Disable the non-deterministic time header when using gzip compression

lib/private/bats.bzl
This allows it to work on Windows as well.
Fixes red main build following #982 
(note that the CI setup for this repo saves GHA quota by not running tests on Windows for all PRs, only when they come from a branch with 'windows' in the name)
Tested by using a little-known feature where Bazel can report the test case names:
```
$ bazel test lib/tests/bats:basic --test_summary=detailed
INFO: Analyzed target //lib/tests/bats:basic (3 packages loaded, 947 targets configured).
INFO: Found 1 test target...
Target //lib/tests/bats:basic up-to-date:
bazel-bin/lib/tests/bats/basic_bats.sh
INFO: Elapsed time: 0.399s, Critical Path: 0.21s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
INFO: Build completed successfully, 3 total actions
//lib/tests/bats:basic …
```
=> fix(bats_test): use env var rather than symbolic link

renovate.json
Renovate does not upgrade pre-commit hooks by default. I think, we should also keep them up to date.
Just enabling it will create a separate PR per hook. In case this becomes too noisy, we can also configure renovate to create a single PR updating all in one.
=> chore(deps): Enable renovate for pre-commit

MODULE.bazel, lib/extensions.bzl
Marking the toolchains extension as reproducible since all underlying tools are already checked for integrity. Saving an entry in the lockfile for that extension.
Marking this has to be conditional to `bazel_features.external_deps.extension_metadata_has_reproducible`, hence bumping `bazel_features` to 1.9.0 which is the version introducing the check (https://github.com/bazel-contrib/bazel_features/releases/tag/v1.9.0)
=> feat(bzlmod): mark toolchains extension as reproducible

docs/transitions.md, lib/transitions.bzl
Forward RunEnvironmentInfo if present, this is useful if the test we are transitioning requires environment variables.
=> feat: Forward RunEnvironmentInfo if present

lib/private/modify_mtree.awk, lib/tests/tar/BUILD.bazel
Provides fix and test case for #978
=> fix(tar): handle strip_prefix of root directory in mtree_mutate

lib/private/tar_toolchain.bzl
Has some windows fixes needed for rules_js
We should test this in Aspect's internal repo before next release, since we're not sure if there's still a regression in #952 - this time we'll do a better job capturing the repro if so
=> chore(tar): update to latest bsdtar-prebuilt

lib/private/BUILD.bazel, lib/private/run_binary.bzl, lib/tests/run_binary/BUILD.bazel
For any `run_binary` including  rules_js `js_run_binary` and npm package `bin` entries.
Ref https://github.com/aspect-build/rules_js/issues/2015
Ref https://github.com/aspect-build/rules_ts/commit/acd9f4f2b31879902bc987cd778950651f359f37
=> feat(run_binary): add resource_set attribute

.aspect/bazelrc/bazel6.bazelrc, .aspect/bazelrc/bazel7.bazelrc, .aspect/bazelrc/performance.bazelrc
=> chore: Move `--nolegacy_external_runfiles` to version specific rc files

docs/write_source_files.md, lib/private/write_source_file.bzl, lib/tests/write_source_files/BUILD.bazel, lib/write_source_files.bzl
This makes it so that developers can add a custom error message to the diff test failure messages when using `write_source_file` and `write_source_files`.
=> feat: Add diff_test_failure_message attribute to write_source_file*

docs/diff_test.md, docs/write_source_files.md, lib/private/BUILD.bazel, lib/private/diff_test.bzl, lib/private/diff_test_tmpl.sh, lib/private/write_source_file.bzl
This makes it possible to pass extra arguments to the diff command that is run in a `diff_test()`.
~When running `bazel run @@//docs:update` I get a diff in all documents to add example `load()` statements. This was added in [stardoc 0.7.0](https://github.com/bazelbuild/stardoc/releases/tag/0.7.0). I'm not sure how it is leaking in to my local environment. :thinking:~
=> feat: Add option to pass args to `diff` command in `diff_test` on Linux/MacOS

lib/private/BUILD.bazel, lib/private/tar_toolchain.bzl, lib/private/utf8_environment.bzl
Replaces #1019 
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/2256 (provided that callers such as rule implementations use this new property)
=> fix: expose LC_ALL variable in tar toolchain

docs/write_source_files.md, lib/write_source_files.bzl
Forgot to plumb this through to the `write_source_files` macro in https://github.com/bazel-contrib/bazel-lib/pull/1032.
=> feat: Add option to pass diff_args in write_source_files macro

.github/workflows/publish.yaml, .github/workflows/release.yml
Allows users to trust that release artifacts are not tampered
=> feat: publish release attestations

.github/workflows/release.yml
Fixes failures in the prior release attempt https://github.com/bazel-contrib/bazel-lib/actions/runs/14582765728/job/40902801105
=> fix(release): override test command, corresponding to ci.yaml

.github/workflows/release.yml
Also rename our upload to 'binaries' to avoid colliding with default upload name 'artifacts'
=> fix(release): upgrade release workflow

.github/workflows/release.yml
The binaries get downloaded to the `go-binaries` folder as `download-artifact` defaults to the name of the GHA artifact.
=> fix(release): name of folder containing binaries

.github/workflows/release_prep.sh
v2.15.2 published with an empty dict in tools/integrity.bzl
=> fix(release): yet another spot that's wrong

lib/private/modify_mtree.awk, lib/private/tar.bzl, lib/tests/tar/BUILD.bazel
Adding bits to allow mtree_mutate to receive a group name or GID and update the file permissions to set `gid` for the tar file
example usage
```
mtree_mutate(
name = "foo",
mtree = "foo",
owner = "65543",
group = "65543",
)
```
=> feat(mtree_mutate): Adding Support for Group / GID to mtree_mutate

.bcr/patches/go_dev_dep.patch, MODULE.bazel, e2e/external_copy_to_directory/app/BUILD.bazel, lib/BUILD.bazel, lib/testing.bzl, lib/tests/BUILD.bazel, lib/tests/copy_to_bin/BUILD.bazel, lib/tests/copy_to_directory/BUILD.bazel, lib/tests/run_binary/BUILD.bazel, lib/tests/run_binary_expansions/BUILD.bazel, lib/tests/stamping/BUILD.bazel, lib/tests/transitions/BUILD.bazel, shlib/lib/BUILD.bazel, shlib/tests/lib_tests/assertions_tests/BUILD.bazel, tools/release/BUILD.bazel
This will become the default in bazel 9, and some packages (like ours) already set this flag to keep ahead of this. This change:
- adds a direct dependency on rules_shell, and changes all in-tree users to use it rather than `native.sh_*`
- bumps some dev dependencies to versions that have also performed this step, so bazel test works now, too. (gazelle and rules_go)
=> feat: fix build for --incompatible_autoload_externally=

docs/repositories.md, lib/private/yq_toolchain.bzl, lib/tests/yq/BUILD.bazel, lib/tests/yq/sample.yaml, tools/yq_mirror_release.sh
This patch adds riscv64 support to yq toolchain. 
The last version 4.33.3 in `lib/private/yq_toolchain.bzl` does not have riscv64 binary releases in yq repository so I added the latest release to it.
=> feat: add riscv64 support to yq toolchain

docs/diff_test.md, lib/private/BUILD.bazel, lib/private/diff_test.bzl, lib/tests/transitions/BUILD.bazel
Shortens a lot of our BUILD files by avoiding an extra write_file call for literal content
=> feat(diff_test): allow inline content for expected

renovate.json
Renovate/pre-commit autoupdate will try to update to an alpha release which we don't want to. Since https://github.com/pre-commit/mirrors-prettier is archived, we won't expect anything beyond that alpha
=> chore: Exclude prettier hook from renovate

.github/workflows/release_prep.sh, e2e/smoke/WORKSPACE, lib/repositories.bzl
772d605 fixed the bzlmod files but not the workspace files. I should note that there doesn't seem to be a way to test this locally, just in CI, which makes it pretty hard to figure out what's broken...
=> feat: apply rules_shell fixes to WORKSPACE

.github/workflows/release.yml
=> chore: allow release workflow to be called from tag.yaml

.gitattributes, docs/jq.md, docs/tar.md, docs/yq.md
User report: the top result on Google is https://github.com/bazel-contrib/bazel-lib/blob/main/docs/tar.md which is now a 404, and I couldn't see any obvious signposts.
=> chore: add back doc redirects

lib/private/copy_directory_toolchain.bzl, lib/private/copy_to_directory_toolchain.bzl, lib/private/coreutils_toolchain.bzl, lib/private/expand_template_toolchain.bzl, lib/private/jq_toolchain.bzl, lib/private/source_toolchains_repo.bzl, lib/private/tar_toolchain.bzl, lib/private/yq_toolchain.bzl, lib/private/zstd_toolchain.bzl
This was removed by Bazel in bazelbuild/bazel@f53608ac3dbfd02cecb4bb78a138badb0d84e311.
=> fix: remove references to incompatible_use_toolchain_transition

.aspect/bazelrc/performance.bazelrc
Reported in https://github.com/bazel-contrib/bazel-lib/pull/1099#issuecomment-2979976616, we now set both options for common. `--build_runfile_links` should be only set for coverage though.
=> fix: --build_runfile_links only for coverage

lib/private/write_source_file.bzl
https://github.com/bazel-contrib/bazel-lib/issues/367
e.g. 
```bat
C:\> mkdir dir1
C:\> D:
D:\> cd c:\dir1
D:\> C:
C:\dir1>
```
instead it'll behave properly:
```bat
C:\> mkdir dir1
C:\> D:
D:\> cd /d c:\dir1
C:\dir1>
```
=> fix: write_source_file on Windows when workspace is on different drive than the bazel user folder

lib/private/docs.bzl
This macro only works when it is invoked from within a repository that has an explicit dependency on @platforms. This repo needs to be pulled in manually nowadays, meaning that it is no longer guaranteed to be available. By wrapping this in Label(), we force resolution using the MODULE.bazel declared in aspect-bazel-lib itself.
=> fix: Wrap reference to @platforms in Label()

lib/private/tar_toolchain.bzl
Ideally this should not be in bazel-lib, see https://github.com/bazel-contrib/tar.bzl/issues/33
=> chore(deps): upgrade bsdtar to 3.8.1

docs/repositories.md, lib/private/yq_toolchain.bzl, tools/yq_mirror_release.sh
Partially addresses https://github.com/bazel-contrib/bazel-lib/issues/1076
Upstream has introduced support for windows_arm64 recently, so it can be referenced now.
=> chore: add windows_arm64 support to yq

lib/private/tar_toolchain.bzl
bsdtar has been patched to support CRLF delimited mtree files. Use this on Windows.
=> fix: use bsdtar 3.8.1-fix1 on windows for CRLF fixes

MODULE.bazel
Attempting to use this repo with bazel 6.4.1 results in:
```
ERROR: https://bcr.bazel.build/modules/rules_jvm_external/6.1/MODULE.bazel:89:13: name 'use_repo_rule' is not defined
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> aspect_bazel_lib@2.21.0 -> stardoc@0.7.1 -> rules_jvm_external@6.1: error executing MODULE.bazel file for rules_jvm_external@6.1
```
Document the minimum requirement of bazel 6.5.0. This is already configured in the CI matrix.
=> chore: be explicit that we require bazel 6.5.0

.aspect/workflows/config.yaml, .bazelrc
Allows us to drastically simplify the GitHub Actions setup.
Note, we no longer explicitly pass any `--enable_bzlmod` or `--enable_workspace` flags, so we naturally get some WORKSPACE testing on Bazel 6, and bzlmod testing on Bazel 7 and Bazel 8. This doesn't assert on every combination and might miss some defects, but I think it's sufficient.
=> chore(ci): run Linux testing on Buildkite

lib/private/utils.bzl
Invalid repo names lead to repo rule invalidation.
Fixes #1183
=> fix: use a valid repo name in is_bzlmod_enabled

.aspect/workflows/config.yaml, .bcr/presubmit.yml, .github/workflows/release_prep.sh, WORKSPACE.bazel, lib/tests/run_binary_expansions/expansions.sh, lib/tests/transitions/BUILD.bazel
Before 3.0 final we can drop this maintenance burden
=> chore: test on Bazel 9, drop Bazel 6
