docs/expand_make_vars.md
lib/private/expand_make_vars.bzl
lib/tests/BUILD.bazel

feat: expand_template does execpath and vars substitutions

---

.github/workflows/release.yml
BUILD.bazel
README.md
internal_deps.bzl

refactor: simplify release

---

docs/jq.md
lib/jq.bzl

fix: allow tags/visibility on jq rule

---

docs/jq.md
lib/jq.bzl
lib/private/jq.bzl
lib/tests/jq/BUILD.bazel
lib/tests/jq/merge_filter.txt

@gregmagolan || @alexeagle 
I need to use a dynamically generated filter file for the angular cli build.

feat: load jq filter from file

---

lib/private/copy_file.bzl
lib/private/copy_to_directory.bzl

so we don't hit the file path length limit of xcopy
Same as https://github.com/bazelbuild/rules_nodejs/pull/3295

fix: use robocopy in copy_file#is_directory and copy_to_directory

---

.bazelci/presumbit.yml

@alexeagle 
Addresses https://github.com/bazelbuild/continuous-integration/issues/1313

build: add a presubmit.yml file for bazel buildkite ci

---

.pre-commit-config.yaml
docs/paths.md
lib/private/copy_to_directory.bzl
lib/private/expand_make_vars.bzl
lib/private/paths.bzl
lib/private/utils.bzl
lib/tests/jq/BUILD.bazel
lib/tests/paths_test.bzl
lib/tests/utils_test.bzl

@alexeagle 
See: https://buildkite.com/bazel/bazel-lib/builds/4#9229dcdf-05e4-415c-bd93-9cc028fa8582

fix: fix buildifier 5.0.0 errors

---

.prettierignore
docs/write_source_files.md
lib/private/write_source_files.bzl
lib/tests/write_source_files/BUILD.bazel
lib/tests/write_source_files/e_dir/e.js
lib/write_source_files.bzl

Not yet implemented for windows.

feat: write to source folders

---

lib/private/write_source_file.bzl

Fix write_source_files on windows

---

docs/copy_file.md
lib/copy_directory.bzl
lib/copy_file.bzl
lib/private/copy_directory.bzl
lib/private/copy_file.bzl

Same spirit as copy_directory_action. This will be very useful downstream.

feat: add copy_file_action helper function to the public API

---

docs/copy_to_bin.md
lib/private/copy_to_bin.bzl

This will be very useful in rules_js

feat: add copy_to_bin_action for use in other rules

---

lib/private/copy_to_bin.bzl

Slight tweak on that last commit

refactor: split copy_to_bin_action into copy_file_to_bin_action and copy_files_to_bin_actions

---

lib/private/jq_toolchain.bzl
lib/private/yq_toolchain.bzl
lib/repositories.bzl

Downstream you shouldn't have to worry about specifying a version if you just want the default

feat: add default yq and jq versions

---

.github/workflows/bcr.yml
.github/workflows/bcr/metadata.template.json
.github/workflows/bcr/presubmit.yml
.github/workflows/bcr/source.template.json
.github/workflows/create-bcr-entry.mjs

The plan is to turn this into an actions plugin and host on `bazel-contrib`, but want to test run it in bazel-lib first.

feat: post a pr to bcr on successful release

---

BUILD.bazel
lib/private/yq.bzl
lib/tests/yq/BUILD.bazel

Fixes https://github.com/aspect-build/bazel-lib/issues/85

fix: fix a bug where yq failed to build in the root package

---

.github/workflows/bcr.yml

https://github.com/aspect-build/bazel-lib/issues/51
@alexeagle Are we ready for this now?

feat: mirror releases to bcr

---

lib/private/write_source_file.bzl

Fixes https://github.com/aspect-build/bazel-lib/issues/114

fix: add mandatory provider for write_source_files additional_update_targets

---

README.md

https://github.com/aspect-build/bazel-lib/issues/116

chore: improve the readme

---

.github/workflows/workspace_snippet.sh
README.md

add bzlmod usage instructions

---

internal_deps.bzl
lib/repositories.bzl

This allows renovate to understand our dependencies

refactor: remove use of maybe() helper

---

internal_deps.bzl
lib/repositories.bzl

Thanks to @mattem in https://github.com/aspect-build/rules_py/pull/60

refactor: nicer pattern for inlined maybe

---

lib/private/copy_to_bin.bzl

Fixes https://github.com/aspect-build/bazel-lib/issues/154

fix: improve copy_to_bin error messaging when file is in external repo

---

docs/utils.md
lib/private/utils.bzl
lib/tests/utils_test.bzl
lib/utils.bzl

Avoids continued copy-paste of this like https://github.com/aspect-build/rules_ts/blob/main/ts/defs.bzl#L35-L44

Add utility for checking file existence.

---

.aspectci/config.yaml

chore: add Aspect CI configuration

---

docs/BUILD.bazel
docs/testing.md
lib/BUILD.bazel
lib/private/BUILD.bazel
lib/testing.bzl
lib/tests/BUILD.bazel

Useful for basic smoke tests of bazel outputs

feat: add utility for asserting that a file contains a string

---

BUILD.bazel
lib/private/write_source_file.bzl

From https://github.com/aspect-build/bazel-lib/pull/214.
@jfirebaugh thanks for catching this.

fix: fix a bug where multiple files were not written at the root package

---

WORKSPACE
docs/BUILD.bazel
docs/platform_utils.md
lib/BUILD.bazel
lib/platform_utils.bzl
lib/private/BUILD.bazel
lib/private/copy_common.bzl
lib/private/copy_directory.bzl
lib/private/copy_file.bzl
lib/private/copy_to_directory.bzl
lib/private/local_config_platform.bzl
lib/private/platform_utils.bzl
lib/repositories.bzl

Also add platform_utils to public API which is used under the hood

fix: don't generate @aspect_bazel_lib_local_config_platform repository as it is a leaky abstraction for rule consumers and not just rule authors

---

lib/private/utils.bzl
lib/tests/utils_test.bzl

Before landing we should confirm and file an upstream issue for this

fix: workaround bazel bug?

---

lib/private/copy_to_directory.bzl

Slightly easier to read and understand imo

chore: nit cleanup in copy_to_directory _longest_glob_match helper

---

e2e/bzlmod/.bazeliskrc

aspect cli bazelisk rc config breaks bzlmod presubmit: https://buildkite.com/bazel/bcr-presubmit/builds/714

build: fix bzlmod presubmit failure with bazel version

---

docs/BUILD.bazel
docs/diff_test.md
lib/private/docs/BUILD.bazel

Also adds one missing gitignore

fix: add diff_test to docs

---

BUILD.bazel
lib/tests/copy_file/BUILD.bazel
lib/tests/transitions/BUILD.bazel

Pre-factor to building a golang based copy_to_directory binary

chore: run gazelle for golang

---

tools/copy_to_directory/main.go

Pre-factor to https://github.com/aspect-build/bazel-lib/pull/321 (tested there)
This change needs to land and then a patch release cut so that the toolchain in #321 can be updated to use the new feature.

Add hardlink support to copy_to_directory binary tool

---

deps.bzl
go.mod
go.sum
tools/common/file.go
tools/copy_directory/BUILD.bazel
tools/copy_directory/main.go
tools/copy_to_directory/BUILD.bazel
tools/copy_to_directory/main.go

fix: use custom realpath function in copy_directory and copy_to_directory since github.com/yookoala/realpath has bugs on Windows

---

.aspect/bazelrc/ci.bazelrc

fix(bazelrc-presets): restore 60s progress rate on CI

---

docs/write_source_files.md
lib/private/write_source_file.bzl

docs(write_source_file): specify the name of the generated diff_test

---

.bazeliskrc
.bazelversion

chore: update to Bazel 6.1.2 and Aspect CLI 5.3.4

---

tools/expand_template/BUILD.bazel

fix: remove missing toolchain load

---

lib/tests/copy_file/BUILD.bazel

See https://github.com/aspect-build/rules_js/issues/1055

test: add tests for copying hidden files

---

MODULE.bazel
lib/private/docs.bzl

Newest stardoc has fixed it, so we want to be able to opt-in.
It would be nice to detect this automatically but I don't have a clever idea how to do that.
cc @fmeum
---

fix(stardoc): stop skipping stardoc w bzlmod

---

docs/paths.md
lib/private/paths.bzl

docs: clarify rlocationpath

---

lib/private/repo_utils.bzl

Using this downstream in rules_oci

fix(windows): use HOMEPATH in place of HOME

---

lib/private/copy_directory_toolchain.bzl
lib/private/copy_to_directory_toolchain.bzl
lib/private/expand_template_toolchain.bzl
lib/private/repo_utils.bzl
tools/release.bzl

Add basic support for freebsd_amd64.
Ran `bazel build tools:{copy_to_directory,copy_directory}`, confirmed that a FreeBSD executable is generated

feat: add freebsd support

---

internal_deps.bzl

Reverts aspect-build/bazel-lib#441

Revert "chore(deps): update dependency io_bazel_stardoc to v0.5.6"

---

docs/jq.md
docs/repo_utils.md
lib/jq.bzl

None, this is copied from an executable (green) example

chore: document JQ_BIN make var

---

.aspect/workflows/terraform/workflows.tf
.circleci/config.yml

chore: update to Aspect Workflows 5.7.0-rc10

---

e2e/copy_to_directory/.bazeliskrc

On windows, we can't turn on the Aspect CLI currently as we don't have a release
---

fix: green up red main CI

---

.aspect/workflows/terraform/workflows.tf
.circleci/config.yml

scaling_polling_frequency > 1 supported on GCP in 5.7.1 release

chore: update to Aspect Workflows 5.7.1

---

.github/workflows/release_prep.sh
MODULE.bazel

It doesn't work properly with Publish To BCR app parsing of the module file.
---
Reasoning it's okay since it reverts

chore: revert fancy release automation

---

.github/workflows/release_prep.sh
lib/private/expand_template_toolchain.bzl

Also fix an error that was getting reported in our release pipeline
---

chore: pick up new expand_template go binary

---

e2e/bzlmod_write_source_files_external/.aspect/bazelrc/correctness.bazelrc
e2e/copy_to_directory/.aspect/bazelrc/correctness.bazelrc
e2e/coreutils/.aspect/bazelrc/correctness.bazelrc

fix: check in generated bazelrcs

---

e2e/copy_to_directory/.aspect/bazelrc/correctness.bazelrc
e2e/coreutils/.aspect/bazelrc/correctness.bazelrc

chore: fix red ci

---

docs/expand_make_vars.md
docs/expand_template.md
lib/BUILD.bazel
lib/expand_template.bzl
lib/tests/expand_template/BUILD.bazel

feat: expand_template allows inline template content

---

.pre-commit-config.yaml
BUILD.bazel
lib/BUILD.bazel
lib/private/copy_to_directory.bzl
lib/private/diff_test.bzl
lib/private/expand_template.bzl
lib/private/run_binary.bzl
lib/private/write_source_file.bzl
lib/repo_utils.bzl
lib/repositories.bzl
lib/testing.bzl
lib/tests/BUILD.bazel
lib/tests/copy_directory/BUILD.bazel
lib/tests/copy_file/BUILD.bazel
lib/tests/copy_to_directory/BUILD.bazel
lib/tests/copy_to_directory_action/BUILD.bazel
lib/tests/copy_to_directory_bin_action/BUILD.bazel
lib/tests/expand_template/BUILD.bazel
lib/tests/jq/BUILD.bazel
lib/tests/run_binary/BUILD.bazel
lib/tests/stamping/BUILD.bazel
lib/tests/transitions/BUILD.bazel
lib/tests/write_source_files/BUILD.bazel
lib/tests/write_source_files/build_files_in_outs/BUILD.bazel
lib/tests/write_source_files/write_source_file_test.bzl
lib/tests/yq/BUILD.bazel
tools/BUILD.bazel
tools/release.bzl

It needs to match the one CI runs, see https://github.com/aspect-build/bazel-lib/pull/489
https://github.com/aspect-build/bazel-lib/actions/runs/6357283303/job/17268197322

chore: update pre-commit buildifier

---

lib/private/tar_toolchain.bzl

this changes the order in which toolchains get registered/listed in the build file to allow the host toolchain to be a fallback that is always fetched if the platform-specific toolchains don't match.

fix: make host toolchain a fallback toolchain

---

.aspect/workflows/terraform/workflows.tf

chore: bump to latest version of Aspect Workflows starter image

---

.github/workflows/ci.yaml

chore: run CI on 2.x branch

---

e2e/smoke/BUILD.bazel

Didn't catch this before adding 2.x to run on CI.

fix: fix bad import

---

docs/copy_directory.md
docs/copy_file.md
docs/copy_to_bin.md
lib/private/copy_directory.bzl
lib/private/copy_file.bzl
lib/private/copy_to_bin.bzl

chore: remove is_windows attributes

---

docs/copy_directory.md
docs/copy_file.md
docs/copy_to_directory.md
lib/BUILD.bazel
lib/copy_directory.bzl
lib/copy_file.bzl
lib/copy_to_directory.bzl
lib/private/copy_common.bzl
lib/private/copy_directory.bzl
lib/private/copy_file.bzl
lib/private/copy_to_directory.bzl

feat: expose a config_setting for copy execution_requirements (#606)

---

.aspect/workflows/config.yaml
.aspect/workflows/terraform/workflows.tf
.circleci/config.yml

Set new scale_out_factor to 7 to cover all tasks created

chore: upgrade to Aspect Workflows 5.8.2

---

lib/private/tar.bzl
lib/tests/tar/BUILD.bazel

feat: support treeartifacts

---

lib/private/tar.bzl
lib/tests/tar/BUILD.bazel

feat: support treeartifacts (#630)

---

.gitattributes
.github/workflows/release_prep.sh
tools/version.bzl

Makes it match bazelbuild/rules_proto#189

refactor: move 'git archive' configuration to .gitattributes

---

docs/repositories.md
lib/private/coreutils_toolchain.bzl

- New feature or functionality (change which adds functionality)**

Upgrade coreutils and add darwin arm64 binary

---

lib/private/extension_utils.bzl

Prefactor for https://github.com/aspect-build/bazel-lib/pull/661

fix: fix a bug where toolchain repositories were potentially duplicated

---

docs/tar.md
lib/tar.bzl

fix: expose tar_lib as public

---

lib/private/tar.bzl

feat: introduce extension compression mapping

---

.aspect/workflows/config.yaml
.aspect/workflows/terraform/workflows.tf
.circleci/config.yml

Similar to https://github.com/aspect-build/rules_js/pull/1392 and https://github.com/aspect-build/rules_jasmine/pull/102

chore: run Aspect Workflows setup step on small instances

---

docs/tar.md
lib/tar.bzl
lib/tests/tar/BUILD.bazel

chore: improve docs about mtree mutation

---

.aspect/workflows/config.yaml
tools/release/BUILD.bazel
tools/release/delivery.sh

Tested here: https://app.circleci.com/pipelines/github/aspect-build/bazel-lib/2324/workflows/78b48612-d9fa-4404-a7df-064891bc2d29

chore: enable workflows delivery on demostration target

---

.github/workflows/ci.bazelrc
BUILD.bazel
lib/private/BUILD.bazel
lib/private/bats.bzl
tools/format/BUILD.bazel
tools/format/noop.sh

fix: create windows launcher for bats

---

lib/tests/bats/additional_lib.bats

test: fix timeout

---

.aspect/workflows/bazelrc
.aspect/workflows/config.yaml
.aspect/workflows/terraform/.terraform.lock.hcl
.aspect/workflows/terraform/main.tf
.aspect/workflows/terraform/workflows.tf
.circleci/config.yml
.pre-commit-config.yaml

Also
- enabled configure task
- updated versions of pre-commit hooks
- fix remote_download_minimal bazelrc flags `common` issue (related to https://github.com/bazelbuild/bazel/pull/20720)

chore: upgrade to Aspect Workflows 5.9.0.rc.10

---

lib/repositories.bzl
tools/version.bzl

I checked this by changing the logic and adding a print statement

Fix prerelease

---

lib/paths.bzl

chore: upgrade bash rlocation lib to v3

---

docs/write_source_files.md
lib/write_source_files.bzl

---
Fixes #723 
TODO: Update docs?
Make WriteSourceFileInfo public so end user rules can participate in additional_update_targets
I've tested this by adding the provider to rules in our private repo and it works great

FR-723: make WriteSourceFileInfo public

---

README.md
docs/bats.md
lib/bats.bzl

docs: add bats docs

---

.circleci/BUILD.bazel

chore: green up CI

---

docs/tar.md
lib/BUILD.bazel
lib/tar.bzl
lib/tests/tar/BUILD.bazel

- New feature or functionality (https://github.com/aspect-build/bazel-lib/issues/653)

feat: support location expansion in tar

---

lib/BUILD.bazel

Hoisting this from rules_js since it is generic and maybe useful for other rule sets.
---
TODO

feat: add //lib:enable_runfiles config_setting

---

tools/expand_template/main.go
tools/integrity.bzl

---
Bug fix (change which fixes an issue)
https://bazelbuild.slack.com/archives/C04281DTLH0/p1713216473704709
The old regex didn't support spaces in the workspace status entries, this should hopefully fix that 🎉 
Updated link to new regex101 examples

support spaces in status

---

.github/workflows/conventional-commits.yml

Ensure that our workflow runs for PRs that originate from an untrusted fork. See https://github.com/amannn/action-semantic-pull-request#event-triggers

refactor: update conventional-commits.yml

---

.github/workflows/ci.bazelrc

Fixes red rbe on main: https://github.com/aspect-build/bazel-lib/actions/runs/9075317514/job/24936228216

ci: green up rbe on main

---

lib/private/paths.bzl

The `bazel_skylib` `paths.join` contains a lot of logic unnecessary in this case that degrades performance.
See https://github.com/bazelbuild/bazel-skylib/blob/1.7.1/lib/paths.bzl#L90-L98
Also removed duplicate `len(..)` calls and removed the use of `zip` and `basename` which both construct a new array.
---

perf: reduce concatenation in relative_path

---

docs/jq.md
lib/jq.bzl

I think this was wrong? Wish our examples were also executable...

fix(docs): description of jq example didn't match behavior

---

e2e/smoke/BUILD.bazel
e2e/smoke/MODULE.bazel

We landed a test in #898 that seems totally broken. Disabling to get a release out.

chore: green up CI on main branch

---

.github/workflows/ci.yaml

adopts https://github.com/bazel-contrib/rules-template/pull/124

chore: stable job name for branch protection

---

lib/private/tar_toolchain.bzl

see https://github.com/aspect-build/bsdtar-prebuilt/pull/10

fix(tar): pick up bsdtar windows fix

---

docs/copy_to_bin.md
lib/copy_to_bin.bzl
lib/private/copy_to_directory.bzl
lib/windows_utils.bzl

And a few to bazelbuild/rules_nodejs

chore: update old reference to aspect-build/bazel-lib

---

lib/private/copy_directory_toolchain.bzl
lib/private/copy_to_directory_toolchain.bzl
lib/private/expand_template_toolchain.bzl
tools/release/release.bzl

Supports https://github.com/bazel-contrib/bazel-lib/issues/1076

feat: add `windows_arm64` binaries for built-in toolchains

---

docs/expand_make_vars.md
lib/private/expand_variables.bzl
lib/private/run_binary.bzl
lib/tests/run_binary_expansions/BUILD.bazel
lib/tests/run_binary_expansions/expansions_golden
lib/tests/run_binary_expansions/expansions_golden_bzlmod

Support `$<` in `expand_variables` and `run_binary`

feat: support $< in expand_variables

---

docs/repositories.md
lib/private/coreutils_toolchain.bzl

Triggered by https://github.com/bazel-contrib/rules_oci/issues/826

chore(deps): update coreutils to v0.1.0

---

tools/common/BUILD.bazel
tools/common/clonefile_darwin.go
tools/common/clonefile_linux.go
tools/common/clonefile_stub.go
tools/common/copy.go

Also cleanup the implementation a bit and expose the helper, it can be useful for other tools we build

feat: Add clonefile implementation for linux
